{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/lphud\/button\/init(coder:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/lphud\/button\/init(coder:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/init(coder:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"required","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aDecoder"},{"text":": ","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"aDecoder","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An unarchiver object."}]}]}],"kind":"parameters"}],"abstract":[{"text":"Creates a new button with data in an unarchiver.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button"]]},"metadata":{"roleHeading":"Initializer","externalID":"c:@M@LPHUD@objc(cs)Button(im)initWithCoder:","modules":[{"name":"LPHUD"}],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"title":"init(coder:)","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button":{"navigatorTitle":[{"kind":"identifier","text":"Button"}],"type":"topic","title":"Button","url":"\/documentation\/lphud\/button","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Button"}],"kind":"symbol","abstract":[],"role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button/init(coder:)":{"url":"\/documentation\/lphud\/button\/init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"type":"topic","title":"init(coder:)","abstract":[{"text":"Creates a new button with data in an unarchiver.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/init(coder:)","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","kind":"symbol","title":"LPHUD","url":"\/documentation\/lphud","abstract":[],"type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithCoder:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithCoder:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":" *) ","kind":"text"},{"text":"aDecoder","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button\/title","value":"Button","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button\/fragments","op":"replace","value":[{"kind":"identifier","text":"Button"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1init(coder:)\/title","value":"initWithCoder:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1init(coder:)\/fragments"}]}]}