{"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/setTitleColor(_:for:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Sets the color of the title to use for the specified state.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button"]]},"sections":[],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","modules":[{"name":"LPHUD"}],"externalID":"c:@M@LPHUD@objc(cs)Button(im)setTitleColor:forState:","title":"setTitleColor(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTitleColor"},{"kind":"text","text":"("},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UIControlState","text":"State","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"setTitleColor:forState:"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/button\/settitlecolor(_:for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/lphud\/button\/settitlecolor(_:for:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setTitleColor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"color","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"state"},{"text":": ","kind":"text"},{"text":"UIControl","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"text":"State","preciseIdentifier":"c:@E@UIControlState","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"color","content":[{"inlineContent":[{"type":"text","text":"The color of the title to use for the specified state."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The state that uses the specified color. The possible values are described in UIControl.State."}]}],"name":"state"}]}],"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button/setTitleColor(_:for:)":{"url":"\/documentation\/lphud\/button\/settitlecolor(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setTitleColor"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlState","text":"State"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setTitleColor:forState:"}],"type":"topic","title":"setTitleColor(_:for:)","abstract":[{"text":"Sets the color of the title to use for the specified state.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/setTitleColor(_:for:)","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button":{"navigatorTitle":[{"kind":"identifier","text":"Button"}],"type":"topic","title":"Button","url":"\/documentation\/lphud\/button","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Button"}],"kind":"symbol","abstract":[],"role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","kind":"symbol","title":"LPHUD","url":"\/documentation\/lphud","abstract":[],"type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"setTitleColor:forState:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"setTitleColor:forState:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"setTitleColor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"color"},{"text":" ","kind":"text"},{"text":"forState:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@UIControlState","text":"UIControlState","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"state","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"setTitleColor:forState:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1setTitleColor(_:for:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"setTitleColor:forState:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1setTitleColor(_:for:)\/fragments"},{"op":"replace","value":"Button","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button\/fragments","value":[{"kind":"identifier","text":"Button"}]}]}]}