{"metadata":{"externalID":"c:@M@LPHUD@objc(cs)RoundProgressView(im)init","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"roleHeading":"Initializer","title":"init()","role":"symbol","modules":[{"name":"LPHUD"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/roundprogressview\/init()"]},{"paths":["\/documentation\/lphud\/roundprogressview\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"()"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/init()","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundProgressView":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView","navigatorTitle":[{"kind":"identifier","text":"RoundProgressView"}],"type":"topic","kind":"symbol","role":"symbol","title":"RoundProgressView","url":"\/documentation\/lphud\/roundprogressview","abstract":[{"text":"A progress view for showing definite progress by filling up a circle (pie chart).","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoundProgressView","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"type":"topic","url":"\/documentation\/lphud","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","abstract":[],"role":"collection","title":"LPHUD","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundProgressView/init()":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/init()","url":"\/documentation\/lphud\/roundprogressview\/init()","kind":"symbol","type":"topic","abstract":[],"title":"init()","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"init"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView\/title","value":"RoundProgressView","op":"replace"},{"value":[{"kind":"identifier","text":"RoundProgressView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView~1init()\/title","value":"init"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView~1init()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}