{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"required","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"text":"coder","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"aDecoder","kind":"internalParam"},{"kind":"text","text":": "},{"text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Initializer","modules":[{"name":"LPHUD"}],"title":"init(coder:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"text":")","kind":"text"}],"externalID":"c:@M@LPHUD@objc(cs)RoundProgressView(im)initWithCoder:","symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/roundprogressview\/init(coder:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/lphud\/roundprogressview\/init(coder:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/init(coder:)"},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundProgressView/init(coder:)":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/init(coder:)","url":"\/documentation\/lphud\/roundprogressview\/init(coder:)","kind":"symbol","type":"topic","abstract":[],"title":"init(coder:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"type":"topic","url":"\/documentation\/lphud","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","abstract":[],"role":"collection","title":"LPHUD","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundProgressView":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView","navigatorTitle":[{"kind":"identifier","text":"RoundProgressView"}],"type":"topic","kind":"symbol","role":"symbol","title":"RoundProgressView","url":"\/documentation\/lphud\/roundprogressview","abstract":[{"text":"A progress view for showing definite progress by filling up a circle (pie chart).","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoundProgressView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithCoder:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier","text":"NSCoder"},{"text":" *) ","kind":"text"},{"text":"aDecoder","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView~1init(coder:)\/title","value":"initWithCoder:"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView\/title","op":"replace","value":"RoundProgressView"},{"value":[{"text":"RoundProgressView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView\/fragments"}]}]}