{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/didMoveToWindow()"},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","title":"didMoveToWindow()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMoveToWindow"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"didMoveToWindow","kind":"identifier"}],"externalID":"c:@M@FlyHUD@objc(cs)ProgressView(im)didMoveToWindow","modules":[{"name":"FlyHUD"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView"]]},"variants":[{"paths":["\/documentation\/flyhud\/progressview\/didmovetowindow()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/flyhud\/progressview\/didmovetowindow()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Tells the view that its window object changed."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didMoveToWindow","kind":"identifier"},{"kind":"text","text":"()"}]}]}],"references":{"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/didMoveToWindow()":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/didMoveToWindow()","type":"topic","title":"didMoveToWindow()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"didMoveToWindow"}],"url":"\/documentation\/flyhud\/progressview\/didmovetowindow()","abstract":[{"type":"text","text":"Tells the view that its window object changed."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didMoveToWindow","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD":{"url":"\/documentation\/flyhud","role":"collection","kind":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","title":"FlyHUD","type":"topic","abstract":[]},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProgressView"}],"kind":"symbol","title":"ProgressView","abstract":[{"type":"text","text":"A view that depicts the progress of a task over time."}],"url":"\/documentation\/flyhud\/progressview","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ProgressView"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"didMoveToWindow","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"didMoveToWindow","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"didMoveToWindow"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"didMoveToWindow","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1didMoveToWindow()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1didMoveToWindow()\/fragments","value":[{"kind":"text","text":"- "},{"text":"didMoveToWindow","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView\/title","value":"ProgressView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView\/fragments","value":[{"text":"ProgressView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}