{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","symbolKind":"method","externalID":"c:@M@FlyHUD@objc(cs)ProgressView(im)didMoveToSuperview","modules":[{"name":"FlyHUD"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"didMoveToSuperview"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMoveToSuperview"},{"text":"()","kind":"text"}],"title":"didMoveToSuperview()"},"abstract":[{"type":"text","text":"Tells the view that its superview changed."}],"identifier":{"url":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/didMoveToSuperview()","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMoveToSuperview"},{"kind":"text","text":"()"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/flyhud\/progressview\/didmovetosuperview()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/flyhud\/progressview\/didmovetosuperview()"]}],"references":{"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/didMoveToSuperview()":{"kind":"symbol","navigatorTitle":[{"text":"didMoveToSuperview","kind":"identifier"}],"title":"didMoveToSuperview()","type":"topic","role":"symbol","url":"\/documentation\/flyhud\/progressview\/didmovetosuperview()","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/didMoveToSuperview()","abstract":[{"text":"Tells the view that its superview changed.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMoveToSuperview"},{"kind":"text","text":"()"}]},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProgressView"}],"kind":"symbol","title":"ProgressView","abstract":[{"type":"text","text":"A view that depicts the progress of a task over time."}],"url":"\/documentation\/flyhud\/progressview","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ProgressView"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD":{"url":"\/documentation\/flyhud","role":"collection","kind":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","title":"FlyHUD","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"didMoveToSuperview"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didMoveToSuperview","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"didMoveToSuperview"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1didMoveToSuperview()\/title","value":"didMoveToSuperview"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1didMoveToSuperview()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didMoveToSuperview","kind":"identifier"}]},{"op":"replace","value":"ProgressView","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView\/title"},{"value":[{"text":"ProgressView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}