{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView"},"variants":[{"paths":["\/documentation\/lphud\/contentview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/lphud\/contentview"]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView"],"kind":"relationships"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/DisplayLinkDelegate","doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSCoding","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended","doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSObject","doc:\/\/org.cocoapods.LPHUD\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.LPHUD\/s7CVarArgP","doc:\/\/org.cocoapods.LPHUD\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.LPHUD\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.LPHUD\/SQ","doc:\/\/org.cocoapods.LPHUD\/SH","doc:\/\/org.cocoapods.LPHUD\/s8SendableP","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.LPHUD\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIUserActivityRestoring"]}],"metadata":{"title":"ContentView","modules":[{"name":"LPHUD"}],"navigatorTitle":[{"kind":"identifier","text":"ContentView"}],"externalID":"c:@M@LPHUD@objc(cs)ContentView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ContentView","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContentView"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Structures","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Layout-swift.struct"]},{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/button","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/contentColor","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/detailsLabel","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/indicatorPosition-swift.property","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/isHidden","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/isMotionEffectsEnabled","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/label","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/layout-swift.property","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/mode-swift.property","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/observedProgress","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/progress"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/commonInit()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/updateScreenInDisplayLink()"]},{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Alignment","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/IndicatorPosition-swift.enum","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Mode-swift.enum"],"title":"Enumerations"}],"sections":[],"abstract":[{"text":"The content view of the HUD object. The view containing the labels, button and indicator (or customView).","type":"text"},{"text":" ","type":"text"},{"text":"The HUD object places the content in this view in front of any background views.","type":"text"}],"kind":"symbol","references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/isHidden":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"hidden"}],"role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isHidden","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/isHidden","kind":"symbol","url":"\/documentation\/lphud\/contentview\/ishidden","title":"isHidden"},"doc://org.cocoapods.LPHUD/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.LPHUD/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/initWithCoder:":{"role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"url":"\/documentation\/lphud\/contentview\/initwithcoder:","kind":"symbol","title":"initWithCoder:","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/initWithCoder:"},"doc://org.cocoapods.LPHUD/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.LPHUD/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.LPHUD/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://org.cocoapods.LPHUD/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://org.cocoapods.LPHUD/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/updateScreenInDisplayLink()":{"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/updateScreenInDisplayLink()","kind":"symbol","title":"updateScreenInDisplayLink()","url":"\/documentation\/lphud\/contentview\/updatescreenindisplaylink()","abstract":[{"text":"Refreshing the progress only every frame draw.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateScreenInDisplayLink"},{"kind":"text","text":"()"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/indicatorPosition-swift.property":{"title":"indicatorPosition","kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/indicatorPosition-swift.property","url":"\/documentation\/lphud\/contentview\/indicatorposition-swift.property","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"indicatorPosition"},{"kind":"text","text":": "},{"text":"IndicatorPosition","kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD11ContentViewC17IndicatorPositionO"}],"abstract":[{"type":"text","text":"The horizontal and vertical position of the indicator relative to other views. "},{"code":"Defaults to .top","type":"codeVoice"},{"text":".","type":"text"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/observedProgress":{"abstract":[{"type":"text","text":"The Progress object feeding the progress information to the progress indicator."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/observedProgress","url":"\/documentation\/lphud\/contentview\/observedprogress","kind":"symbol","type":"topic","role":"symbol","title":"observedProgress","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"observedProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Progress","preciseIdentifier":"c:objc(cs)NSProgress"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BackgroundView":{"url":"\/documentation\/lphud\/backgroundview","navigatorTitle":[{"kind":"identifier","text":"BackgroundView"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView","title":"BackgroundView","abstract":[{"text":"The view to use as the background of the HUD.","type":"text"},{"type":"text","text":" "},{"text":"HUD adds the background view as a subview behind all other views and uses its current frame location.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BackgroundView","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/Alignment":{"title":"ContentView.Alignment","navigatorTitle":[{"text":"Alignment","kind":"identifier"}],"url":"\/documentation\/lphud\/contentview\/alignment","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Alignment"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Alignment"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"},"doc://org.cocoapods.LPHUD/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem","type":"unresolvable"},"doc://org.cocoapods.LPHUD/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s8SendableP","title":"Swift.Sendable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/layout-swift.property":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"HUD layout configuration. eg: offset, margin, padding, etc."}],"title":"layout","role":"symbol","url":"\/documentation\/lphud\/contentview\/layout-swift.property","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/layout-swift.property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"layout"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD11ContentViewC6LayoutV","text":"Layout"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/progress":{"abstract":[{"text":"The progress of the progress indicator, from 0.0 to 1.0. ","type":"text"},{"code":"Defaults to 0.0","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/progress","url":"\/documentation\/lphud\/contentview\/progress","kind":"symbol","type":"topic","role":"symbol","title":"progress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"progress","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/contentColor":{"title":"contentColor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contentColor"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/lphud\/contentview\/contentcolor","abstract":[{"type":"text","text":"A color that gets forwarded to all labels and supported indicators. Also sets the tintColor for custom views."},{"text":" ","type":"text"},{"type":"text","text":"Set to nil to manage color individually. "},{"code":"Defaults to semi-translucent white","type":"codeVoice"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/contentColor"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/Layout-swift.struct":{"url":"\/documentation\/lphud\/contentview\/layout-swift.struct","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Layout-swift.struct","abstract":[],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Layout"}],"title":"ContentView.Layout","navigatorTitle":[{"text":"Layout","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.LPHUD/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.LPHUD/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate","type":"unresolvable"},"doc://org.cocoapods.LPHUD/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/DisplayLinkDelegate":{"title":"DisplayLinkDelegate","url":"\/documentation\/lphud\/displaylinkdelegate","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/DisplayLinkDelegate","abstract":[{"text":"The methods adopted by the object that allows your app to synchronize its drawing to the refresh rate of the display.","type":"text"}],"navigatorTitle":[{"text":"DisplayLinkDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DisplayLinkDelegate"}]},"doc://org.cocoapods.LPHUD/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/commonInit()":{"url":"\/documentation\/lphud\/contentview\/commoninit()","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/commonInit()","abstract":[{"type":"text","text":"Common initialization method."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"commonInit","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","title":"commonInit()","kind":"symbol","role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/mode-swift.property":{"url":"\/documentation\/lphud\/contentview\/mode-swift.property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5LPHUD11ContentViewC4ModeO","text":"Mode","kind":"typeIdentifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"HUD operation mode. "},{"type":"codeVoice","code":"Default to .indicator(.large)"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/mode-swift.property","title":"mode"},"doc://org.cocoapods.LPHUD/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","kind":"symbol","title":"LPHUD","url":"\/documentation\/lphud","abstract":[],"type":"topic","role":"collection"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUDExtended":{"navigatorTitle":[{"kind":"identifier","text":"HUDExtended"}],"abstract":[{"type":"text","text":"Protocol describing the "},{"type":"codeVoice","code":"h"},{"text":" extension points for HUD extended types.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"HUDExtended","kind":"identifier"}],"url":"\/documentation\/lphud\/hudextended","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended","kind":"symbol","role":"symbol","title":"HUDExtended"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/button":{"abstract":[{"type":"text","text":"A button that is placed below the labels. Visible only if a target \/ action is added and a title is assigned."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"button"},{"kind":"text","text":": "},{"text":"Button","preciseIdentifier":"c:@M@LPHUD@objc(cs)Button","kind":"typeIdentifier"}],"title":"button","url":"\/documentation\/lphud\/contentview\/button","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/button"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/Mode-swift.enum":{"title":"ContentView.Mode","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Mode-swift.enum","navigatorTitle":[{"text":"Mode","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Mode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/lphud\/contentview\/mode-swift.enum"},"doc://org.cocoapods.LPHUD/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace","type":"unresolvable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView":{"title":"ContentView","role":"symbol","abstract":[{"type":"text","text":"The content view of the HUD object. The view containing the labels, button and indicator (or customView)."},{"text":" ","type":"text"},{"text":"The HUD object places the content in this view in front of any background views.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ContentView","kind":"identifier"}],"navigatorTitle":[{"text":"ContentView","kind":"identifier"}],"url":"\/documentation\/lphud\/contentview","kind":"symbol","type":"topic"},"doc://org.cocoapods.LPHUD/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://org.cocoapods.LPHUD/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/IndicatorPosition-swift.enum":{"navigatorTitle":[{"text":"IndicatorPosition","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/IndicatorPosition-swift.enum","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndicatorPosition"}],"role":"symbol","abstract":[],"title":"ContentView.IndicatorPosition","kind":"symbol","url":"\/documentation\/lphud\/contentview\/indicatorposition-swift.enum"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/isMotionEffectsEnabled":{"title":"isMotionEffectsEnabled","abstract":[{"type":"text","text":"When enabled, the contentView center gets slightly affected by the device accelerometer data. "},{"code":"Defaults to false","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/isMotionEffectsEnabled","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isMotionEffectsEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/lphud\/contentview\/ismotioneffectsenabled"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/initWithFrame:":{"type":"topic","url":"\/documentation\/lphud\/contentview\/initwithframe:","role":"symbol","abstract":[],"title":"initWithFrame:","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/initWithFrame:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification"},"doc://org.cocoapods.LPHUD/SQ":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.LPHUD/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/detailsLabel":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/detailsLabel","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detailsLabel","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier","text":"UILabel"}],"title":"detailsLabel","kind":"symbol","abstract":[{"type":"text","text":"A label that holds an optional details message displayed below the labelText message. The details text can span multiple lines."}],"role":"symbol","type":"topic","url":"\/documentation\/lphud\/contentview\/detailslabel"},"doc://org.cocoapods.LPHUD/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/label":{"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/label","kind":"symbol","title":"label","url":"\/documentation\/lphud\/contentview\/label","abstract":[{"type":"text","text":"A label that holds an optional short message to be displayed below the activity indicator. The HUD is automatically resized to fit the entire text."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"label","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"ContentView","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ContentView","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ContentView","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/isHidden"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/initWithCoder:","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/initWithFrame:"]}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView"]}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"ContentView","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView","text":"BackgroundView","preciseIdentifier":"c:@M@LPHUD@objc(cs)BackgroundView","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ContentView~1isHidden\/title","value":"hidden"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ContentView~1isHidden\/fragments","op":"replace","value":[{"text":"hidden","kind":"identifier"}]},{"value":"BackgroundView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView\/fragments","value":[{"kind":"identifier","text":"BackgroundView"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ContentView\/title","op":"replace","value":"ContentView"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ContentView\/fragments","op":"replace","value":[{"text":"ContentView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}