{"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/lphud\/baseview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/lphud\/baseview"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BaseView","kind":"identifier"}],"languages":["swift"]}]}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView\/init(coder:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView\/init(frame:)"],"title":"Initializers"},{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView\/commonInit()"],"title":"Instance Methods"}],"metadata":{"title":"BaseView","roleHeading":"Class","modules":[{"name":"LPHUD"}],"symbolKind":"class","navigatorTitle":[{"text":"BaseView","kind":"identifier"}],"externalID":"c:@M@LPHUD@objc(cs)BaseView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseView"}],"role":"symbol"},"abstract":[{"type":"text","text":"A base view only provides one "},{"code":"commonInit","type":"codeVoice"},{"type":"text","text":" method."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD"]]},"kind":"symbol","sections":[],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.LPHUD\/objc(cs)UIView"],"title":"Inherits From","kind":"relationships"},{"title":"Inherited By","kind":"relationships","type":"inheritedBy","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView"]},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSCoding","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended","doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSObject","doc:\/\/org.cocoapods.LPHUD\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.LPHUD\/s7CVarArgP","doc:\/\/org.cocoapods.LPHUD\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.LPHUD\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.LPHUD\/SQ","doc:\/\/org.cocoapods.LPHUD\/SH","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.LPHUD\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo"}],"references":{"doc://org.cocoapods.LPHUD/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.LPHUD/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.LPHUD/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.LPHUD/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.LPHUD/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.LPHUD/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSCoding"},"doc://org.cocoapods.LPHUD/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.LPHUD/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.LPHUD/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s7CVarArgP"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BaseView/init(frame:)":{"title":"init(frame:)","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView\/init(frame:)","url":"\/documentation\/lphud\/baseview\/init(frame:)","role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":")","kind":"text"}]},"doc://org.cocoapods.LPHUD/objc(cs)UIView":{"title":"UIView","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(cs)UIView"},"doc://org.cocoapods.LPHUD/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.LPHUD/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView":{"type":"topic","url":"\/documentation\/lphud\/activityindicatorview","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActivityIndicatorView"}],"navigatorTitle":[{"kind":"identifier","text":"ActivityIndicatorView"}],"role":"symbol","title":"ActivityIndicatorView","abstract":[{"type":"text","text":"A view that shows that a task is in progress."}]},"doc://org.cocoapods.LPHUD/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItem"},"doc://org.cocoapods.LPHUD/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.LPHUD/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BaseView/init(coder:)":{"role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView\/init(coder:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"text":")","kind":"text"}],"url":"\/documentation\/lphud\/baseview\/init(coder:)","type":"topic","title":"init(coder:)"},"doc://org.cocoapods.LPHUD/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUDExtended":{"role":"symbol","type":"topic","title":"HUDExtended","url":"\/documentation\/lphud\/hudextended","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HUDExtended"}],"abstract":[{"type":"text","text":"Protocol describing the "},{"type":"codeVoice","code":"h"},{"type":"text","text":" extension points for HUD extended types."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended","navigatorTitle":[{"text":"HUDExtended","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/SH"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.LPHUD/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/5UIKit23UITraitChangeObservableP"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BaseView/commonInit()":{"type":"topic","url":"\/documentation\/lphud\/baseview\/commoninit()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"commonInit"},{"text":"()","kind":"text"}],"title":"commonInit()","abstract":[{"text":"The default implementation of this method does nothing.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Subclasses can override it to perform additional actions after superview initialization."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView\/commonInit()","role":"symbol"},"doc://org.cocoapods.LPHUD/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/SQ"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD":{"navigatorTitle":[{"kind":"identifier","text":"HUD"}],"title":"HUD","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","url":"\/documentation\/lphud\/hud","abstract":[{"text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HUD","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView","type":"topic","navigatorTitle":[{"text":"ProgressView","kind":"identifier"}],"abstract":[{"type":"text","text":"A view that depicts the progress of a task over time."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ProgressView","kind":"identifier"}],"role":"symbol","title":"ProgressView","url":"\/documentation\/lphud\/progressview","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BackgroundView":{"role":"symbol","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BackgroundView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView","navigatorTitle":[{"kind":"identifier","text":"BackgroundView"}],"url":"\/documentation\/lphud\/backgroundview","type":"topic","title":"BackgroundView"},"doc://org.cocoapods.LPHUD/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearance"},"doc://org.cocoapods.LPHUD/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s23CustomStringConvertibleP"},"doc://org.cocoapods.LPHUD/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSObject"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BaseView":{"role":"symbol","type":"topic","title":"BaseView","url":"\/documentation\/lphud\/baseview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BaseView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView","kind":"symbol","abstract":[{"type":"text","text":"A base view only provides one "},{"type":"codeVoice","code":"commonInit"},{"type":"text","text":" method."}],"navigatorTitle":[{"kind":"identifier","text":"BaseView"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"type":"topic","url":"\/documentation\/lphud","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","title":"LPHUD","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"BaseView","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"BaseView"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"BaseView","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView\/init(coder:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView\/init(frame:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/objc(cs)UIView"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView"],"type":"inheritedBy"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"BaseView","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BaseView~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrame:"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BaseView~1init(frame:)\/fragments"},{"op":"replace","value":"ActivityIndicatorView","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView\/fragments","op":"replace","value":[{"text":"ActivityIndicatorView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BaseView~1init(coder:)\/title","value":"initWithCoder:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BaseView~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/title","value":"HUD"},{"value":[{"text":"HUD","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/title","op":"replace","value":"ProgressView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/fragments","value":[{"text":"ProgressView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView\/title","value":"BackgroundView","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView\/fragments","op":"replace","value":[{"kind":"identifier","text":"BackgroundView"}]},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BaseView\/title","op":"replace","value":"BaseView"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BaseView\/fragments","value":[{"text":"BaseView","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}