{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didMoveToWindow"},{"kind":"text","text":"()"}],"modules":[{"name":"LPHUD"}],"roleHeading":"Instance Method","title":"didMoveToWindow()","externalID":"c:@M@LPHUD@objc(cs)ProgressView(im)didMoveToWindow","symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"didMoveToWindow","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didMoveToWindow"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Tells the view that its window object changed."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/progressview\/didmovetowindow()"]},{"paths":["\/documentation\/lphud\/progressview\/didmovetowindow()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/didMoveToWindow()"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProgressView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView","abstract":[{"type":"text","text":"A view that depicts the progress of a task over time."}],"type":"topic","title":"ProgressView","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ProgressView"}],"kind":"symbol","url":"\/documentation\/lphud\/progressview"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"abstract":[],"role":"collection","kind":"symbol","type":"topic","title":"LPHUD","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","url":"\/documentation\/lphud"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/didMoveToWindow()":{"navigatorTitle":[{"text":"didMoveToWindow","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMoveToWindow"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Tells the view that its window object changed."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/didMoveToWindow()","url":"\/documentation\/lphud\/progressview\/didmovetowindow()","title":"didMoveToWindow()","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"didMoveToWindow","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"ProgressView","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/fragments","value":[{"kind":"identifier","text":"ProgressView"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView~1didMoveToWindow()\/title","value":"didMoveToWindow","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView~1didMoveToWindow()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didMoveToWindow"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}