{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contentView"},{"text":": ","kind":"text"},{"text":"ContentView","preciseIdentifier":"c:@M@LPHUD@objc(cs)ContentView","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/lphud\/hud\/contentview"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"LPHUD"}],"role":"symbol","title":"contentView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"contentView","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)ContentView","text":"ContentView","kind":"typeIdentifier"}],"externalID":"s:5LPHUD3HUDC11contentViewAA07ContentD0Cvp","roleHeading":"Instance Property","symbolKind":"property"},"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/contentView","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"The view containing the labels, button and indicator (or customView). The HUD object places the content in this view in front of any background views."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD"]]},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContentView"}],"type":"topic","navigatorTitle":[{"text":"ContentView","kind":"identifier"}],"abstract":[{"text":"The content view of the HUD object. The view containing the labels, button and indicator (or customView).","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The HUD object places the content in this view in front of any background views."}],"kind":"symbol","role":"symbol","url":"\/documentation\/lphud\/contentview","title":"ContentView"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD":{"title":"HUD","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HUD","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"HUD","kind":"identifier"}],"url":"\/documentation\/lphud\/hud","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","abstract":[{"type":"text","text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages."}],"role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/contentView":{"url":"\/documentation\/lphud\/hud\/contentview","title":"contentView","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The view containing the labels, button and indicator (or customView). The HUD object places the content in this view in front of any background views."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ContentView","kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)ContentView"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/contentView"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"role":"collection","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","type":"topic","kind":"symbol","title":"LPHUD","abstract":[],"url":"\/documentation\/lphud"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"ContentView","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ContentView\/title"},{"value":[{"kind":"identifier","text":"ContentView"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ContentView\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/title","op":"replace","value":"HUD"},{"value":[{"text":"HUD","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/fragments"}]}]}