{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD"]]},"variants":[{"paths":["\/documentation\/lphud\/hud\/showstatus(to:duration:animated:mode:label:offset:populator:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/showStatus(to:duration:animated:mode:label:offset:populator:)"},"abstract":[{"type":"text","text":"Creates a new HUD. adds it to provided view and shows it. And auto hides the HUD after a duration."}],"metadata":{"role":"symbol","symbolKind":"method","externalID":"s:5LPHUD3HUDC10showStatus2to8duration8animated4mode5label6offset9populatorACSo6UIViewC_SdSbAA11ContentViewC4ModeOSSSgSo7CGPointVyACcSgtFZ","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"showStatus","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"text":"ContentView","kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)ContentView"},{"kind":"text","text":"."},{"preciseIdentifier":"s:5LPHUD11ContentViewC4ModeO","kind":"typeIdentifier","text":"Mode"},{"text":", ","kind":"text"},{"text":"label","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"offset","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"populator"},{"kind":"text","text":": (("},{"text":"HUD","kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?) -> "},{"text":"HUD","kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD"}],"title":"showStatus(to:duration:animated:mode:label:offset:populator:)","roleHeading":"Type Method","modules":[{"name":"LPHUD"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@discardableResult","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showStatus"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"kind":"text","text":" "},{"text":"view","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"duration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":" = 2.0, ","kind":"text"},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)ContentView","text":"ContentView","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD11ContentViewC4ModeO","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Mode-swift.enum","text":"Mode"},{"kind":"text","text":" = .text, "},{"text":"label","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"offset"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"text":" = .zero, ","kind":"text"},{"kind":"externalParam","text":"populator"},{"kind":"text","text":": (("},{"text":"HUD","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")? = nil) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD","text":"HUD","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The view that the HUD will be added to"}],"type":"paragraph"}],"name":"view"},{"name":"duration","content":[{"type":"paragraph","inlineContent":[{"text":"The total duration of the show, measured in seconds. Duration must be greater than 0.0. ","type":"text"},{"code":"Default to 2.0","type":"codeVoice"},{"text":".","type":"text"}]}]},{"name":"animated","content":[{"inlineContent":[{"type":"text","text":"If set to true the HUD will appear using the default animation."},{"type":"text","text":" "},{"text":"If set to false the HUD will not use animations while appearing. ","type":"text"},{"code":"Default to true","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"mode","content":[{"type":"paragraph","inlineContent":[{"text":"HUD operation mode. ","type":"text"},{"type":"codeVoice","code":"Default to .indicator(.large)"},{"type":"text","text":"."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"An optional short message to be displayed below the activity indicator. The HUD is automatically resized to fit the entire text."},{"text":" ","type":"text"},{"type":"text","text":"If the text is too long it will get clipped by displaying “…” at the end. If left unchanged or set to “”, then no message is displayed."}],"type":"paragraph"}],"name":"label"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The contentView offset relative to the center of the view. You can use ","type":"text"},{"type":"codeVoice","code":".h.maxOffset"},{"text":" to move the HUD","type":"text"},{"text":" ","type":"text"},{"text":"all the way to the screen edge in each direction. ","type":"text"},{"code":"Default to .zero","type":"codeVoice"},{"type":"text","text":"."}]}],"name":"offset"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A block or function that populates the ","type":"text"},{"code":"HUD","type":"codeVoice"},{"type":"text","text":", which is passed into the block as an argument. "},{"code":"Default to nil","type":"codeVoice"},{"type":"text","text":"."}]}],"name":"populator"}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"text":"A reference to the created HUD.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"name":"Note","style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"Default animation "},{"type":"codeVoice","code":"HUD.Animation(style:.fade,duration:0.3,damping:.disable)"}],"type":"paragraph"}]},{"style":"note","name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"If ","type":"text"},{"type":"codeVoice","code":"isCountEnabled"},{"type":"text","text":" is set to true, the activity count is incremented by 1 when showing the HUD. The activity count is decremented by 1 when hiding the HUD."}]}]}]}],"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD":{"type":"topic","title":"HUD","abstract":[{"type":"text","text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages."}],"url":"\/documentation\/lphud\/hud","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HUD"}],"navigatorTitle":[{"kind":"identifier","text":"HUD"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/showStatus(to:duration:animated:mode:label:offset:populator:)":{"title":"showStatus(to:duration:animated:mode:label:offset:populator:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"mode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ContentView","preciseIdentifier":"c:@M@LPHUD@objc(cs)ContentView"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD11ContentViewC4ModeO","text":"Mode"},{"kind":"text","text":", "},{"text":"label","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"populator"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD","kind":"typeIdentifier","text":"HUD"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?) -> ","kind":"text"},{"text":"HUD","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD","kind":"typeIdentifier"}],"abstract":[{"text":"Creates a new HUD. adds it to provided view and shows it. And auto hides the HUD after a duration.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/showStatus(to:duration:animated:mode:label:offset:populator:)","type":"topic","url":"\/documentation\/lphud\/hud\/showstatus(to:duration:animated:mode:label:offset:populator:)","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","kind":"symbol","abstract":[],"title":"LPHUD","url":"\/documentation\/lphud","role":"collection"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ContentView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView","title":"ContentView","abstract":[{"type":"text","text":"The content view of the HUD object. The view containing the labels, button and indicator (or customView)."},{"text":" ","type":"text"},{"type":"text","text":"The HUD object places the content in this view in front of any background views."}],"type":"topic","kind":"symbol","url":"\/documentation\/lphud\/contentview","navigatorTitle":[{"text":"ContentView","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/Mode-swift.enum":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Mode","kind":"identifier"}],"title":"ContentView.Mode","navigatorTitle":[{"kind":"identifier","text":"Mode"}],"abstract":[],"url":"\/documentation\/lphud\/contentview\/mode-swift.enum","kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Mode-swift.enum","type":"topic"}},"variantOverrides":[{"patch":[{"value":"HUD","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/fragments","value":[{"kind":"identifier","text":"HUD"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ContentView\/title","value":"ContentView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ContentView\/fragments","value":[{"text":"ContentView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}