{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/intrinsicContentSize"},"sections":[],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"modules":[{"name":"LPHUD"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"role":"symbol","externalID":"c:@M@LPHUD@objc(cs)ProgressView(py)intrinsicContentSize","title":"intrinsicContentSize","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/lphud\/progressview\/intrinsiccontentsize"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/lphud\/progressview\/intrinsiccontentsize"]}],"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"type":"topic","url":"\/documentation\/lphud","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","title":"LPHUD","role":"collection"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/intrinsicContentSize":{"kind":"symbol","type":"topic","title":"intrinsicContentSize","url":"\/documentation\/lphud\/progressview\/intrinsiccontentsize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/intrinsicContentSize","role":"symbol","abstract":[]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView","type":"topic","navigatorTitle":[{"text":"ProgressView","kind":"identifier"}],"abstract":[{"type":"text","text":"A view that depicts the progress of a task over time."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ProgressView","kind":"identifier"}],"role":"symbol","title":"ProgressView","url":"\/documentation\/lphud\/progressview","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"intrinsicContentSize"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"intrinsicContentSize","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"intrinsicContentSize","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView~1intrinsicContentSize\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView~1intrinsicContentSize\/fragments","value":[{"text":"intrinsicContentSize","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ProgressView","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/title"},{"op":"replace","value":[{"text":"ProgressView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/fragments"}]}]}