{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label"]]},"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label\/bounds","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The bounds rectangle, which describes the label’s location and size in its own coordinate system."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bounds","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/label\/bounds"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/lphud\/label\/bounds"]}],"metadata":{"navigatorTitle":[{"text":"bounds","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","title":"bounds","role":"symbol","externalID":"c:@M@LPHUD@objc(cs)Label(py)bounds","modules":[{"name":"LPHUD"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bounds","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}]},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/Label":{"navigatorTitle":[{"text":"Label","kind":"identifier"}],"type":"topic","url":"\/documentation\/lphud\/label","role":"symbol","title":"Label","abstract":[{"text":"A view that displays one or more lines of informational text.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Label","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Label/bounds":{"title":"bounds","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label\/bounds","type":"topic","abstract":[{"text":"The bounds rectangle, which describes the label’s location and size in its own coordinate system.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bounds","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"}],"url":"\/documentation\/lphud\/label\/bounds","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"bounds","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","kind":"symbol","abstract":[],"title":"LPHUD","url":"\/documentation\/lphud","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"bounds","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"bounds"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":" ","kind":"text"},{"text":"bounds","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Label\/title","value":"Label","op":"replace"},{"value":[{"kind":"identifier","text":"Label"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Label\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Label~1bounds\/title","op":"replace","value":"bounds"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Label~1bounds\/fragments","op":"replace","value":[{"kind":"identifier","text":"bounds"}]}]}]}