{"abstract":[{"text":"A view that shows that a task is in progress.","type":"text"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BaseView"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorViewable","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)NSCoding","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/HUDExtended","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)NSObject","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.FlyHUD\/s7CVarArgP","doc:\/\/org.cocoapods.FlyHUD\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.FlyHUD\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.FlyHUD\/SQ","doc:\/\/org.cocoapods.FlyHUD\/SH","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.FlyHUD\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ActivityIndicatorView","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"type":"aside","name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"You control when an activity indicator animates by calling the startAnimating() and stopAnimating()","type":"text"},{"type":"text","text":" "},{"type":"text","text":"methods. To automatically hide the activity indicator when animation stops, set the hidesWhenStopped"},{"text":" ","type":"text"},{"type":"text","text":"property to true. You can set the color of the activity indicator by using the color property."}]}]}],"kind":"content"}],"metadata":{"roleHeading":"Class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActivityIndicatorView"}],"navigatorTitle":[{"kind":"identifier","text":"ActivityIndicatorView"}],"modules":[{"name":"FlyHUD"}],"externalID":"c:@M@FlyHUD@objc(cs)ActivityIndicatorView","symbolKind":"class","title":"ActivityIndicatorView"},"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/init(style:size:populator:)","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/init(styleable:size:populator:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/bounds","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/color","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/hidesWhenStopped","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/intrinsicContentSize","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/isAnimating","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/lineWidth","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/style-swift.property","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/trackColor"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/commonInit()","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/didMoveToWindow()","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/startAnimating()","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/stopAnimating()","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/traitCollectionDidChange(_:)"]},{"identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/Style-swift.enum"],"title":"Enumerations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/flyhud\/activityindicatorview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/flyhud\/activityindicatorview"]}],"references":{"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView/hidesWhenStopped":{"title":"hidesWhenStopped","abstract":[{"text":"A Boolean value that controls whether the activity indicator is hidden when the animation is stopped.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/hidesWhenStopped","url":"\/documentation\/flyhud\/activityindicatorview\/hideswhenstopped","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hidesWhenStopped"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD":{"url":"\/documentation\/flyhud","role":"collection","kind":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","title":"FlyHUD","type":"topic","abstract":[]},"doc://org.cocoapods.FlyHUD/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView/traitCollectionDidChange(_:)":{"type":"topic","url":"\/documentation\/flyhud\/activityindicatorview\/traitcollectiondidchange(_:)","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/traitCollectionDidChange(_:)","kind":"symbol","title":"traitCollectionDidChange(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"traitCollectionDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITraitCollection","text":"UITraitCollection","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"traitCollectionDidChange:"}],"abstract":[]},"doc://org.cocoapods.FlyHUD/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification"},"doc://org.cocoapods.FlyHUD/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.FlyHUD/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView/didMoveToWindow()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMoveToWindow"},{"text":"()","kind":"text"}],"title":"didMoveToWindow()","role":"symbol","kind":"symbol","abstract":[{"text":"Tells the view that its window object changed.","type":"text"}],"url":"\/documentation\/flyhud\/activityindicatorview\/didmovetowindow()","type":"topic","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/didMoveToWindow()","navigatorTitle":[{"kind":"identifier","text":"didMoveToWindow"}]},"doc://org.cocoapods.FlyHUD/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAppearance"},"doc://org.cocoapods.FlyHUD/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView/commonInit()":{"title":"commonInit()","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Common initialization method."}],"url":"\/documentation\/flyhud\/activityindicatorview\/commoninit()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"commonInit","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/commonInit()"},"doc://org.cocoapods.FlyHUD/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/SQ"},"doc://org.cocoapods.FlyHUD/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/SH"},"doc://org.cocoapods.FlyHUD/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/5UIKit23UITraitChangeObservableP"},"doc://org.cocoapods.FlyHUD/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)NSObject"},"doc://org.cocoapods.FlyHUD/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.FlyHUD/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.FlyHUD\/s23CustomStringConvertibleP"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView/isAnimating":{"url":"\/documentation\/flyhud\/activityindicatorview\/isanimating","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isAnimating","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"isAnimating","kind":"symbol","abstract":[{"type":"text","text":"A Boolean value indicating whether the activity indicator is currently running its animation."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/isAnimating","type":"topic"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView/intrinsicContentSize":{"navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"url":"\/documentation\/flyhud\/activityindicatorview\/intrinsiccontentsize","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/intrinsicContentSize","abstract":[{"text":"The natural size for the receiving view, considering only properties of the view itself.","type":"text"}],"title":"intrinsicContentSize"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView/init(styleable:size:populator:)":{"url":"\/documentation\/flyhud\/activityindicatorview\/init(styleable:size:populator:)","abstract":[{"text":"Creates an activity indicator view with the specified style.","type":"text"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"styleable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActivityIndicatorViewStyleable","preciseIdentifier":"s:6FlyHUD30ActivityIndicatorViewStyleableP"},{"text":", ","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"text":", ","kind":"text"},{"text":"populator","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FlyHUD@objc(cs)ActivityIndicatorView","text":"ActivityIndicatorView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/init(styleable:size:populator:)","title":"init(styleable:size:populator:)","kind":"symbol","type":"topic"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView/color":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/color","title":"color","url":"\/documentation\/flyhud\/activityindicatorview\/color","abstract":[{"text":"The color of the activity indicator.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"color","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"!","kind":"text"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/BaseView":{"kind":"symbol","navigatorTitle":[{"text":"BaseView","kind":"identifier"}],"title":"BaseView","type":"topic","role":"symbol","url":"\/documentation\/flyhud\/baseview","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BaseView","abstract":[{"text":"A base view only provides one ","type":"text"},{"type":"codeVoice","code":"commonInit"},{"text":" method.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BaseView","kind":"identifier"}]},"doc://org.cocoapods.FlyHUD/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)NSCoding"},"doc://org.cocoapods.FlyHUD/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView/bounds":{"url":"\/documentation\/flyhud\/activityindicatorview\/bounds","navigatorTitle":[{"text":"bounds","kind":"identifier"}],"title":"bounds","kind":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/bounds","abstract":[{"text":"The bounds rectangle, which describes the view’s location and size in its own coordinate system.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bounds","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}],"role":"symbol"},"doc://org.cocoapods.FlyHUD/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.FlyHUD/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView/trackColor":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"title":"trackColor","url":"\/documentation\/flyhud\/activityindicatorview\/trackcolor","abstract":[{"type":"text","text":"The track color of the activity indicator."}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/trackColor","type":"topic","role":"symbol"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView/stopAnimating()":{"type":"topic","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/stopAnimating()","abstract":[{"type":"text","text":"Stops the animation of the activity indicator."}],"url":"\/documentation\/flyhud\/activityindicatorview\/stopanimating()","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"stopAnimating","kind":"identifier"},{"text":"()","kind":"text"}],"title":"stopAnimating()"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView/startAnimating()":{"role":"symbol","url":"\/documentation\/flyhud\/activityindicatorview\/startanimating()","title":"startAnimating()","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/startAnimating()","kind":"symbol","abstract":[{"text":"Starts the animation of the activity indicator.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"startAnimating","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic"},"doc://org.cocoapods.FlyHUD/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace"},"doc://org.cocoapods.FlyHUD/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.FlyHUD/objc(pl)CALayerDelegate":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate"},"doc://org.cocoapods.FlyHUD/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView/initWithFrame:":{"title":"initWithFrame:","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/initWithFrame:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}],"url":"\/documentation\/flyhud\/activityindicatorview\/initwithframe:","type":"topic","kind":"symbol","role":"symbol"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView":{"title":"ActivityIndicatorView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivityIndicatorView"}],"abstract":[{"text":"A view that shows that a task is in progress.","type":"text"}],"navigatorTitle":[{"text":"ActivityIndicatorView","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView","type":"topic","kind":"symbol","url":"\/documentation\/flyhud\/activityindicatorview"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView/initWithCoder:":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/initWithCoder:","type":"topic","title":"initWithCoder:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/flyhud\/activityindicatorview\/initwithcoder:","abstract":[],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}]},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView/style-swift.property":{"url":"\/documentation\/flyhud\/activityindicatorview\/style-swift.property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"preciseIdentifier":"s:6FlyHUD30ActivityIndicatorViewStyleableP","kind":"typeIdentifier","text":"ActivityIndicatorViewStyleable"}],"title":"style","kind":"symbol","abstract":[{"type":"text","text":"The basic appearance of the activity indicator view. The value of this property is a constant that specifies the style of the activity indicator view."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/style-swift.property","type":"topic"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorViewable":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActivityIndicatorViewable"}],"abstract":[{"type":"text","text":"A view that shows that a task is in progress."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorViewable","url":"\/documentation\/flyhud\/activityindicatorviewable","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActivityIndicatorViewable","kind":"identifier"}],"title":"ActivityIndicatorViewable"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/HUDExtended":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/HUDExtended","url":"\/documentation\/flyhud\/hudextended","navigatorTitle":[{"text":"HUDExtended","kind":"identifier"}],"title":"HUDExtended","type":"topic","abstract":[{"type":"text","text":"Protocol describing the "},{"code":"h","type":"codeVoice"},{"text":" extension points for HUD extended types.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"HUDExtended","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.FlyHUD/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView/Style-swift.enum":{"title":"ActivityIndicatorView.Style","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Style","kind":"identifier"}],"abstract":[{"type":"text","text":"The visual style of the activity indicator."}],"navigatorTitle":[{"kind":"identifier","text":"Style"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/Style-swift.enum","type":"topic","url":"\/documentation\/flyhud\/activityindicatorview\/style-swift.enum","kind":"symbol"},"doc://org.cocoapods.FlyHUD/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView/init(style:size:populator:)":{"kind":"symbol","title":"init(style:size:populator:)","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/init(style:size:populator:)","type":"topic","url":"\/documentation\/flyhud\/activityindicatorview\/init(style:size:populator:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:6FlyHUD21ActivityIndicatorViewC5StyleO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"text":", ","kind":"text"},{"text":"populator","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"ActivityIndicatorView","preciseIdentifier":"c:@M@FlyHUD@objc(cs)ActivityIndicatorView","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"abstract":[{"type":"text","text":"Creates an activity indicator view with the specified style."}]},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView/lineWidth":{"url":"\/documentation\/flyhud\/activityindicatorview\/linewidth","abstract":[{"text":"The line width of the activity indicator.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"lineWidth","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/lineWidth","title":"lineWidth","kind":"symbol","type":"topic"},"doc://org.cocoapods.FlyHUD/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://org.cocoapods.FlyHUD/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"ActivityIndicatorView","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"kind":"identifier","text":"ActivityIndicatorView"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ActivityIndicatorView"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/bounds","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/intrinsicContentSize"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/didMoveToWindow()","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/initWithCoder:","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/initWithFrame:","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/traitCollectionDidChange(_:)"]}],"op":"replace"},{"op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BaseView"],"type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"ActivityIndicatorView","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"BaseView","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BaseView","preciseIdentifier":"c:@M@FlyHUD@objc(cs)BaseView"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView~1traitCollectionDidChange(_:)\/title","op":"replace","value":"traitCollectionDidChange:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"traitCollectionDidChange:"}],"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView~1traitCollectionDidChange(_:)\/fragments"},{"value":"didMoveToWindow","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView~1didMoveToWindow()\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView~1didMoveToWindow()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"didMoveToWindow","kind":"identifier"}]},{"op":"replace","value":"intrinsicContentSize","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView~1intrinsicContentSize\/title"},{"value":[{"text":"intrinsicContentSize","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView~1intrinsicContentSize\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BaseView\/title","value":"BaseView"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BaseView\/fragments","op":"replace","value":[{"kind":"identifier","text":"BaseView"}]},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView~1bounds\/title","value":"bounds","op":"replace"},{"value":[{"text":"bounds","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView~1bounds\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView\/title","value":"ActivityIndicatorView","op":"replace"},{"value":[{"text":"ActivityIndicatorView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}