{"variants":[{"paths":["\/documentation\/flyhud\/baseview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/flyhud\/baseview"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BaseView"},"abstract":[{"type":"text","text":"A base view only provides one "},{"type":"codeVoice","code":"commonInit"},{"type":"text","text":" method."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseView"}],"platforms":["iOS"],"languages":["swift"]}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BaseView\/init(coder:)","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BaseView\/init(frame:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BaseView\/commonInit()"]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.FlyHUD\/objc(cs)UIView"]},{"identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/HUD","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView"],"kind":"relationships","type":"inheritedBy","title":"Inherited By"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.FlyHUD\/objc(pl)NSCoding","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/HUDExtended","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)NSObject","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.FlyHUD\/s7CVarArgP","doc:\/\/org.cocoapods.FlyHUD\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.FlyHUD\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.FlyHUD\/SQ","doc:\/\/org.cocoapods.FlyHUD\/SH","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.FlyHUD\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIUserActivityRestoring"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD"]]},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BaseView","kind":"identifier"}],"role":"symbol","title":"BaseView","navigatorTitle":[{"text":"BaseView","kind":"identifier"}],"modules":[{"name":"FlyHUD"}],"externalID":"c:@M@FlyHUD@objc(cs)BaseView","symbolKind":"class","roleHeading":"Class"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.FlyHUD/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.FlyHUD/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/SQ"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/BaseView/commonInit()":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"commonInit"},{"text":"()","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BaseView\/commonInit()","title":"commonInit()","kind":"symbol","url":"\/documentation\/flyhud\/baseview\/commoninit()","abstract":[{"type":"text","text":"The default implementation of this method does nothing."},{"text":" ","type":"text"},{"type":"text","text":"Subclasses can override it to perform additional actions after superview initialization."}]},"doc://org.cocoapods.FlyHUD/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.FlyHUD/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)NSCoding"},"doc://org.cocoapods.FlyHUD/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.FlyHUD/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.FlyHUD/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView":{"title":"ActivityIndicatorView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivityIndicatorView"}],"abstract":[{"text":"A view that shows that a task is in progress.","type":"text"}],"navigatorTitle":[{"text":"ActivityIndicatorView","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView","type":"topic","kind":"symbol","url":"\/documentation\/flyhud\/activityindicatorview"},"doc://org.cocoapods.FlyHUD/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/HUDExtended":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/HUDExtended","url":"\/documentation\/flyhud\/hudextended","navigatorTitle":[{"text":"HUDExtended","kind":"identifier"}],"title":"HUDExtended","type":"topic","abstract":[{"type":"text","text":"Protocol describing the "},{"code":"h","type":"codeVoice"},{"text":" extension points for HUD extended types.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"HUDExtended","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.FlyHUD/objc(cs)UIView":{"title":"UIView","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(cs)UIView"},"doc://org.cocoapods.FlyHUD/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/BaseView/init(frame:)":{"type":"topic","role":"symbol","title":"init(frame:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/flyhud\/baseview\/init(frame:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BaseView\/init(frame:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}]},"doc://org.cocoapods.FlyHUD/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/SH","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusItem","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAppearance","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.FlyHUD\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProgressView"}],"kind":"symbol","title":"ProgressView","abstract":[{"type":"text","text":"A view that depicts the progress of a task over time."}],"url":"\/documentation\/flyhud\/progressview","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ProgressView"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/HUD":{"navigatorTitle":[{"text":"HUD","kind":"identifier"}],"url":"\/documentation\/flyhud\/hud","title":"HUD","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HUD","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/HUD","abstract":[{"type":"text","text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages."}],"role":"symbol"},"doc://org.cocoapods.FlyHUD/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.FlyHUD\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/BaseView":{"kind":"symbol","navigatorTitle":[{"text":"BaseView","kind":"identifier"}],"title":"BaseView","type":"topic","role":"symbol","url":"\/documentation\/flyhud\/baseview","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BaseView","abstract":[{"text":"A base view only provides one ","type":"text"},{"type":"codeVoice","code":"commonInit"},{"text":" method.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BaseView","kind":"identifier"}]},"doc://org.cocoapods.FlyHUD/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusItemContainer","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/BackgroundView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BackgroundView"}],"kind":"symbol","abstract":[{"text":"The view to use as the background of the HUD.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"HUD adds the background view as a subview behind all other views and uses its current frame location."}],"title":"BackgroundView","url":"\/documentation\/flyhud\/backgroundview","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BackgroundView"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView"},"doc://org.cocoapods.FlyHUD/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.FlyHUD\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD":{"url":"\/documentation\/flyhud","role":"collection","kind":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","title":"FlyHUD","type":"topic","abstract":[]},"doc://org.cocoapods.FlyHUD/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UILargeContentViewerItem","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/BaseView/init(coder:)":{"title":"init(coder:)","url":"\/documentation\/flyhud\/baseview\/init(coder:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BaseView\/init(coder:)","abstract":[],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.FlyHUD/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UICoordinateSpace","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","value":"BaseView","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"BaseView"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"BaseView"}]},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BaseView\/init(coder:)","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BaseView\/init(frame:)"]}],"op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.FlyHUD\/objc(cs)UIView"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/HUD","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseView"},{"kind":"text","text":" : "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView\/title","value":"ActivityIndicatorView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView\/fragments","value":[{"kind":"identifier","text":"ActivityIndicatorView"}]},{"value":"initWithFrame:","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BaseView~1init(frame:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BaseView~1init(frame:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView\/title","op":"replace","value":"ProgressView"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView\/fragments","value":[{"kind":"identifier","text":"ProgressView"}],"op":"replace"},{"op":"replace","value":"HUD","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1HUD\/title"},{"op":"replace","value":[{"text":"HUD","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1HUD\/fragments"},{"value":"BaseView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BaseView\/title"},{"value":[{"kind":"identifier","text":"BaseView"}],"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BaseView\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BackgroundView\/title","op":"replace","value":"BackgroundView"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BackgroundView\/fragments","value":[{"text":"BackgroundView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BaseView~1init(coder:)\/title","op":"replace","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BaseView~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}