{"sections":[],"variants":[{"paths":["\/documentation\/lphud"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/lphud"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/DisplayLink","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/KeyboardObserver","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView"],"title":"Classes"},{"title":"Protocols","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorAnimationBuildable","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorViewStyleable","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorViewable","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/DisplayLinkDelegate","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDDelegate","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/KeyboardObservable","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressAnimationBuildable","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressViewStyleable","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressViewable","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RotateViewable"]},{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtension","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/KeyboardInfo"],"title":"Structures"},{"title":"Enumerations","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedCorners"]},{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/CoreFoundation","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ObjectiveC","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Swift","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/UIKit"],"title":"Extended Modules"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","interfaceLanguage":"swift"},"hierarchy":{"paths":[[]]},"kind":"symbol","metadata":{"externalID":"LPHUD","title":"LPHUD","roleHeading":"Framework","role":"collection","modules":[{"name":"LPHUD"}],"symbolKind":"module"},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressViewable":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressViewable","title":"ProgressViewable","url":"\/documentation\/lphud\/progressviewable","type":"topic","abstract":[{"type":"text","text":"A view that depicts the progress of a task over time."}],"kind":"symbol","navigatorTitle":[{"text":"ProgressViewable","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProgressViewable"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HUD"}],"title":"HUD","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","url":"\/documentation\/lphud\/hud","kind":"symbol","abstract":[{"type":"text","text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages."}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HUD"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorAnimationBuildable":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivityIndicatorAnimationBuildable"}],"kind":"symbol","abstract":[{"type":"text","text":"Animation Builder"}],"navigatorTitle":[{"kind":"identifier","text":"ActivityIndicatorAnimationBuildable"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorAnimationBuildable","type":"topic","title":"ActivityIndicatorAnimationBuildable","url":"\/documentation\/lphud\/activityindicatoranimationbuildable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/LPHUDVersionString":{"fragments":[{"kind":"identifier","text":"LPHUDVersionString"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/LPHUDVersionString","role":"symbol","abstract":[],"title":"LPHUDVersionString","url":"\/documentation\/lphud\/lphudversionstring","type":"topic","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/DisplayLink":{"kind":"symbol","abstract":[{"text":"A timer object that allows your app to synchronize its drawing to the refresh rate of the display.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DisplayLink"}],"type":"topic","title":"DisplayLink","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/DisplayLink","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DisplayLink","kind":"identifier"}],"url":"\/documentation\/lphud\/displaylink"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/CoreFoundation":{"url":"\/documentation\/lphud\/corefoundation","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/CoreFoundation","role":"collection","title":"CoreFoundation"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Label":{"navigatorTitle":[{"text":"Label","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label","abstract":[{"text":"A view that displays one or more lines of informational text.","type":"text"}],"title":"Label","kind":"symbol","url":"\/documentation\/lphud\/label","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Label"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUDExtension":{"url":"\/documentation\/lphud\/hudextension","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HUDExtension","kind":"identifier"}],"type":"topic","abstract":[{"text":"Type that acts as a generic extension point for all ","type":"text"},{"type":"codeVoice","code":"HUDExtended"},{"text":" types.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HUDExtension"}],"title":"HUDExtension","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtension","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/DisplayLinkDelegate":{"type":"topic","kind":"symbol","url":"\/documentation\/lphud\/displaylinkdelegate","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/DisplayLinkDelegate","role":"symbol","abstract":[{"type":"text","text":"The methods adopted by the object that allows your app to synchronize its drawing to the refresh rate of the display."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DisplayLinkDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DisplayLinkDelegate"}],"title":"DisplayLinkDelegate"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUDExtended":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"HUDExtended","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/lphud\/hudextended","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended","navigatorTitle":[{"text":"HUDExtended","kind":"identifier"}],"title":"HUDExtended","type":"topic","abstract":[{"type":"text","text":"Protocol describing the "},{"type":"codeVoice","code":"h"},{"type":"text","text":" extension points for HUD extended types."}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ObjectiveC":{"type":"topic","abstract":[],"role":"collection","url":"\/documentation\/lphud\/objectivec","title":"ObjectiveC","kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ObjectiveC"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/KeyboardObserver":{"navigatorTitle":[{"text":"KeyboardObserver","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeyboardObserver"}],"url":"\/documentation\/lphud\/keyboardobserver","type":"topic","title":"KeyboardObserver","abstract":[{"text":"A keyboard observer that tracks the keyboard’s position in your app’s layout.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/KeyboardObserver","role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Swift":{"url":"\/documentation\/lphud\/swift","abstract":[],"title":"Swift","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Swift","type":"topic","role":"collection","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUDDelegate":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDDelegate","abstract":[{"type":"text","text":"A HUD observer that tracks the state of the HUD in your application."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HUDDelegate"}],"url":"\/documentation\/lphud\/huddelegate","kind":"symbol","title":"HUDDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HUDDelegate","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContentView"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContentView"}],"url":"\/documentation\/lphud\/contentview","abstract":[{"text":"The content view of the HUD object. The view containing the labels, button and indicator (or customView).","type":"text"},{"type":"text","text":" "},{"text":"The HUD object places the content in this view in front of any background views.","type":"text"}],"title":"ContentView","role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RotateViewable":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RotateViewable","abstract":[{"type":"text","text":"A rotate view that shows that a task is in progress."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"RotateViewable","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/lphud\/rotateviewable","role":"symbol","title":"RotateViewable","type":"topic","navigatorTitle":[{"text":"RotateViewable","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/LPHUDVersionNumber":{"fragments":[{"text":"LPHUDVersionNumber","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/lphud\/lphudversionnumber","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/LPHUDVersionNumber","title":"LPHUDVersionNumber","type":"topic","abstract":[]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundedCorners":{"navigatorTitle":[{"text":"RoundedCorners","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedCorners","role":"symbol","url":"\/documentation\/lphud\/roundedcorners","kind":"symbol","title":"RoundedCorners","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoundedCorners","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView":{"abstract":[{"text":"A view that shows that a task is in progress.","type":"text"}],"navigatorTitle":[{"text":"ActivityIndicatorView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivityIndicatorView"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView","title":"ActivityIndicatorView","kind":"symbol","url":"\/documentation\/lphud\/activityindicatorview","type":"topic","role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/KeyboardInfo":{"kind":"symbol","type":"topic","abstract":[{"text":"keyboard information model.","type":"text"}],"title":"KeyboardInfo","url":"\/documentation\/lphud\/keyboardinfo","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/KeyboardInfo","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeyboardInfo"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardInfo"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BaseView":{"kind":"symbol","type":"topic","abstract":[{"text":"A base view only provides one ","type":"text"},{"type":"codeVoice","code":"commonInit"},{"type":"text","text":" method."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BaseView"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BaseView","kind":"identifier"}],"title":"BaseView","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView","url":"\/documentation\/lphud\/baseview"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorViewable":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A view that shows that a task is in progress."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ActivityIndicatorViewable","kind":"identifier"}],"navigatorTitle":[{"text":"ActivityIndicatorViewable","kind":"identifier"}],"title":"ActivityIndicatorViewable","role":"symbol","url":"\/documentation\/lphud\/activityindicatorviewable","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorViewable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"abstract":[],"role":"collection","kind":"symbol","type":"topic","title":"LPHUD","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","url":"\/documentation\/lphud"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BackgroundView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BackgroundView"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BackgroundView"}],"kind":"symbol","url":"\/documentation\/lphud\/backgroundview","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView","title":"BackgroundView","type":"topic","abstract":[{"type":"text","text":"The view to use as the background of the HUD."},{"text":" ","type":"text"},{"text":"HUD adds the background view as a subview behind all other views and uses its current frame location.","type":"text"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/KeyboardObservable":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"KeyboardObservable","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A keyboard observer that tracks the keyboard’s position in your app’s layout.","type":"text"}],"navigatorTitle":[{"text":"KeyboardObservable","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/KeyboardObservable","type":"topic","title":"KeyboardObservable","url":"\/documentation\/lphud\/keyboardobservable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressViewStyleable":{"kind":"symbol","abstract":[{"type":"text","text":"The styles permitted for the progress bar."}],"role":"symbol","navigatorTitle":[{"text":"ProgressViewStyleable","kind":"identifier"}],"type":"topic","title":"ProgressViewStyleable","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressViewStyleable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ProgressViewStyleable"}],"url":"\/documentation\/lphud\/progressviewstyleable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button":{"kind":"symbol","url":"\/documentation\/lphud\/button","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button","title":"Button","role":"symbol","abstract":[{"type":"text","text":"A control that executes your custom code in response to user interactions."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Button","kind":"identifier"}],"navigatorTitle":[{"text":"Button","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorViewStyleable":{"title":"ActivityIndicatorViewStyleable","kind":"symbol","abstract":[{"type":"text","text":"The visual style of the activity indicator."}],"type":"topic","navigatorTitle":[{"text":"ActivityIndicatorViewStyleable","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorViewStyleable","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ActivityIndicatorViewStyleable","kind":"identifier"}],"url":"\/documentation\/lphud\/activityindicatorviewstyleable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/UIKit":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/UIKit","kind":"symbol","type":"topic","url":"\/documentation\/lphud\/uikit","role":"collection","title":"UIKit"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressAnimationBuildable":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ProgressAnimationBuildable","kind":"identifier"}],"title":"ProgressAnimationBuildable","navigatorTitle":[{"text":"ProgressAnimationBuildable","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressAnimationBuildable","url":"\/documentation\/lphud\/progressanimationbuildable","type":"topic","abstract":[{"type":"text","text":"Animation Builder"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProgressView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView","abstract":[{"type":"text","text":"A view that depicts the progress of a task over time."}],"type":"topic","title":"ProgressView","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ProgressView"}],"kind":"symbol","url":"\/documentation\/lphud\/progressview"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView"]},{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/LPHUDVersionNumber","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/LPHUDVersionString"],"title":"Variables"}]},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/title","op":"replace","value":"HUD"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/fragments","value":[{"text":"HUD","kind":"identifier"}],"op":"replace"},{"value":"Label","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Label\/title","op":"replace"},{"value":[{"kind":"identifier","text":"Label"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Label\/fragments"},{"value":"ContentView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ContentView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ContentView\/fragments","value":[{"kind":"identifier","text":"ContentView"}],"op":"replace"},{"op":"replace","value":"ActivityIndicatorView","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView\/title"},{"value":[{"text":"ActivityIndicatorView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BaseView\/title","op":"replace","value":"BaseView"},{"op":"replace","value":[{"text":"BaseView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BaseView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView\/title","value":"BackgroundView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView\/fragments","value":[{"kind":"identifier","text":"BackgroundView"}]},{"value":"Button","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button\/fragments","value":[{"text":"Button","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/title","value":"ProgressView","op":"replace"},{"value":[{"kind":"identifier","text":"ProgressView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}