{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"property","externalID":"c:@M@FlyHUD@objc(cs)ActivityIndicatorView(py)intrinsicContentSize","modules":[{"name":"FlyHUD"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"intrinsicContentSize","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}],"title":"intrinsicContentSize"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/intrinsicContentSize"},"abstract":[{"text":"The natural size for the receiving view, considering only properties of the view itself.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/flyhud\/activityindicatorview\/intrinsiccontentsize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/flyhud\/activityindicatorview\/intrinsiccontentsize"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView":{"title":"ActivityIndicatorView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivityIndicatorView"}],"abstract":[{"text":"A view that shows that a task is in progress.","type":"text"}],"navigatorTitle":[{"text":"ActivityIndicatorView","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView","type":"topic","kind":"symbol","url":"\/documentation\/flyhud\/activityindicatorview"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView/intrinsicContentSize":{"navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"url":"\/documentation\/flyhud\/activityindicatorview\/intrinsiccontentsize","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/intrinsicContentSize","abstract":[{"text":"The natural size for the receiving view, considering only properties of the view itself.","type":"text"}],"title":"intrinsicContentSize"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD":{"url":"\/documentation\/flyhud","role":"collection","kind":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","title":"FlyHUD","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"intrinsicContentSize"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"intrinsicContentSize"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"intrinsicContentSize"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView\/title","value":"ActivityIndicatorView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView\/fragments","value":[{"kind":"identifier","text":"ActivityIndicatorView"}]},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView~1intrinsicContentSize\/title","op":"replace","value":"intrinsicContentSize"},{"value":[{"text":"intrinsicContentSize","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView~1intrinsicContentSize\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}