{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/flyhud\/activityindicatorview\/traitcollectiondidchange(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/flyhud\/activityindicatorview\/traitcollectiondidchange(_:)"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"FlyHUD"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"traitCollectionDidChange:"}],"title":"traitCollectionDidChange(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"traitCollectionDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITraitCollection","text":"UITraitCollection","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@FlyHUD@objc(cs)ActivityIndicatorView(im)traitCollectionDidChange:"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/traitCollectionDidChange(_:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"traitCollectionDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"previousTraitCollection","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITraitCollection","text":"UITraitCollection","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView"]]},"references":{"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView":{"title":"ActivityIndicatorView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivityIndicatorView"}],"abstract":[{"text":"A view that shows that a task is in progress.","type":"text"}],"navigatorTitle":[{"text":"ActivityIndicatorView","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView","type":"topic","kind":"symbol","url":"\/documentation\/flyhud\/activityindicatorview"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD":{"url":"\/documentation\/flyhud","role":"collection","kind":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","title":"FlyHUD","type":"topic","abstract":[]},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView/traitCollectionDidChange(_:)":{"type":"topic","url":"\/documentation\/flyhud\/activityindicatorview\/traitcollectiondidchange(_:)","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/traitCollectionDidChange(_:)","kind":"symbol","title":"traitCollectionDidChange(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"traitCollectionDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITraitCollection","text":"UITraitCollection","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"traitCollectionDidChange:"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"traitCollectionDidChange:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"traitCollectionDidChange:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"traitCollectionDidChange:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITraitCollection","text":"UITraitCollection","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"previousTraitCollection"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView\/title","op":"replace","value":"ActivityIndicatorView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView\/fragments","value":[{"text":"ActivityIndicatorView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView~1traitCollectionDidChange(_:)\/title","value":"traitCollectionDidChange:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"traitCollectionDidChange:"}],"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView~1traitCollectionDidChange(_:)\/fragments","op":"replace"}]}]}