{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"intrinsicContentSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","title":"intrinsicContentSize","roleHeading":"Instance Property","modules":[{"name":"LPHUD"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"intrinsicContentSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"symbolKind":"property","navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}],"externalID":"c:@M@LPHUD@objc(cs)RoundProgressView(py)intrinsicContentSize"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/roundprogressview\/intrinsiccontentsize"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/lphud\/roundprogressview\/intrinsiccontentsize"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/intrinsicContentSize"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundProgressView/intrinsicContentSize":{"abstract":[],"title":"intrinsicContentSize","role":"symbol","url":"\/documentation\/lphud\/roundprogressview\/intrinsiccontentsize","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/intrinsicContentSize","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundProgressView":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView","role":"symbol","url":"\/documentation\/lphud\/roundprogressview","type":"topic","abstract":[{"text":"A progress view for showing definite progress by filling up a circle (pie chart).","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RoundProgressView","kind":"identifier"}],"title":"RoundProgressView","navigatorTitle":[{"kind":"identifier","text":"RoundProgressView"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","url":"\/documentation\/lphud","kind":"symbol","title":"LPHUD","type":"topic","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"intrinsicContentSize","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"intrinsicContentSize","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"text":" ","kind":"text"},{"text":"intrinsicContentSize","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView~1intrinsicContentSize\/title","value":"intrinsicContentSize"},{"value":[{"text":"intrinsicContentSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView~1intrinsicContentSize\/fragments"},{"value":"RoundProgressView","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView\/fragments","value":[{"text":"RoundProgressView","kind":"identifier"}]}]}]}