{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/intrinsicContentSize"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/roundedbutton\/intrinsiccontentsize"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/lphud\/roundedbutton\/intrinsiccontentsize"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton"]]},"metadata":{"modules":[{"name":"LPHUD"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@LPHUD@objc(cs)RoundedButton(py)intrinsicContentSize","navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}],"title":"intrinsicContentSize","role":"symbol"},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundedButton/intrinsicContentSize":{"title":"intrinsicContentSize","url":"\/documentation\/lphud\/roundedbutton\/intrinsiccontentsize","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/intrinsicContentSize","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"intrinsicContentSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundedButton":{"title":"RoundedButton","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RoundedButton","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/lphud\/roundedbutton","navigatorTitle":[{"kind":"identifier","text":"RoundedButton"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"type":"topic","url":"\/documentation\/lphud","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","title":"LPHUD","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"intrinsicContentSize","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"intrinsicContentSize","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"}]}]}},{"value":"intrinsicContentSize","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton~1intrinsicContentSize\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton~1intrinsicContentSize\/fragments","op":"replace","value":[{"kind":"identifier","text":"intrinsicContentSize"}]},{"value":"RoundedButton","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton\/fragments","value":[{"text":"RoundedButton","kind":"identifier"}],"op":"replace"}]}]}