{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton"]]},"abstract":[{"type":"text","text":"The rounded corner mode of the button. "},{"type":"codeVoice","code":"Default to .fully"},{"text":".","type":"text"}],"metadata":{"symbolKind":"property","externalID":"s:5LPHUD13RoundedButtonC14roundedCornersAA14BackgroundViewC0bE0Ovp","title":"roundedCorners","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"roundedCorners"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BackgroundView","preciseIdentifier":"c:@M@LPHUD@objc(cs)BackgroundView"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD14BackgroundViewC14RoundedCornersO","text":"RoundedCorners"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"LPHUD"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"roundedCorners"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView","preciseIdentifier":"c:@M@LPHUD@objc(cs)BackgroundView","text":"BackgroundView"},{"text":".","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/RoundedCorners-swift.enum","kind":"typeIdentifier","text":"RoundedCorners","preciseIdentifier":"s:5LPHUD14BackgroundViewC14RoundedCornersO"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/roundedCorners","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/roundedbutton\/roundedcorners"]}],"kind":"symbol","references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundedButton":{"title":"RoundedButton","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RoundedButton","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/lphud\/roundedbutton","navigatorTitle":[{"kind":"identifier","text":"RoundedButton"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BackgroundView":{"role":"symbol","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BackgroundView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView","navigatorTitle":[{"kind":"identifier","text":"BackgroundView"}],"url":"\/documentation\/lphud\/backgroundview","type":"topic","title":"BackgroundView"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BackgroundView/RoundedCorners-swift.enum":{"role":"symbol","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"RoundedCorners","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/RoundedCorners-swift.enum","navigatorTitle":[{"kind":"identifier","text":"RoundedCorners"}],"url":"\/documentation\/lphud\/backgroundview\/roundedcorners-swift.enum","type":"topic","title":"BackgroundView.RoundedCorners"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundedButton/roundedCorners":{"abstract":[{"text":"The rounded corner mode of the button. ","type":"text"},{"code":"Default to .fully","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/lphud\/roundedbutton\/roundedcorners","title":"roundedCorners","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"roundedCorners"},{"text":": ","kind":"text"},{"text":"BackgroundView","kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)BackgroundView"},{"text":".","kind":"text"},{"text":"RoundedCorners","kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD14BackgroundViewC14RoundedCornersO"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/roundedCorners","role":"symbol","type":"topic"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"type":"topic","url":"\/documentation\/lphud","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","title":"LPHUD","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"RoundedButton","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton\/fragments","value":[{"text":"RoundedButton","kind":"identifier"}],"op":"replace"},{"value":"BackgroundView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView\/title"},{"op":"replace","value":[{"text":"BackgroundView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView\/fragments"}]}]}