{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Mode-swift.enum\/indicator(_:)-418k3"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/contentview\/mode-swift.enum\/indicator(_:)-418k3"]}],"kind":"symbol","abstract":[{"type":"text","text":"Creates an activity indicator view with the specified style."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indicator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"style"},{"text":": ","kind":"text"},{"text":"ActivityIndicatorView","kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)ActivityIndicatorView","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView"},{"kind":"text","text":"."},{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/Style-swift.enum","text":"Style","preciseIdentifier":"s:5LPHUD21ActivityIndicatorViewC5StyleO","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)ContentView","text":"ContentView","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView"},{"text":".","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Mode-swift.enum","preciseIdentifier":"s:5LPHUD11ContentViewC4ModeO","kind":"typeIdentifier","text":"Mode"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"style","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A constant that specifies the style of the object to be created. See ActivityIndicatorView.Style for descriptions of the style constants."}]}]}]},{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"An initialized ContentView.Mode constant."}]}],"kind":"content"}],"metadata":{"roleHeading":"Type Method","role":"symbol","modules":[{"name":"LPHUD"}],"title":"indicator(_:)","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"indicator"},{"text":"(","kind":"text"},{"text":"ActivityIndicatorView","kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)ActivityIndicatorView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD21ActivityIndicatorViewC5StyleO","text":"Style"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"ContentView","preciseIdentifier":"c:@M@LPHUD@objc(cs)ContentView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD11ContentViewC4ModeO","text":"Mode"}],"extendedModule":"LPHUD","externalID":"s:5LPHUD11ContentViewC4ModeO9indicatoryAeA017ActivityIndicatorC0C5StyleOFZ"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Mode-swift.enum"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/Mode-swift.enum":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Mode","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Mode"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Mode-swift.enum","type":"topic","title":"ContentView.Mode","abstract":[],"role":"symbol","url":"\/documentation\/lphud\/contentview\/mode-swift.enum"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView/Style-swift.enum":{"navigatorTitle":[{"text":"Style","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/Style-swift.enum","url":"\/documentation\/lphud\/activityindicatorview\/style-swift.enum","kind":"symbol","title":"ActivityIndicatorView.Style","abstract":[{"type":"text","text":"The visual style of the activity indicator."}],"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Style","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView":{"abstract":[{"text":"A view that shows that a task is in progress.","type":"text"}],"navigatorTitle":[{"text":"ActivityIndicatorView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivityIndicatorView"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView","title":"ActivityIndicatorView","kind":"symbol","url":"\/documentation\/lphud\/activityindicatorview","type":"topic","role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContentView"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContentView"}],"url":"\/documentation\/lphud\/contentview","abstract":[{"text":"The content view of the HUD object. The view containing the labels, button and indicator (or customView).","type":"text"},{"type":"text","text":" "},{"text":"The HUD object places the content in this view in front of any background views.","type":"text"}],"title":"ContentView","role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"abstract":[],"role":"collection","kind":"symbol","type":"topic","title":"LPHUD","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","url":"\/documentation\/lphud"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/Mode-swift.enum/indicator(_:)-418k3":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Mode-swift.enum\/indicator(_:)-418k3","abstract":[{"text":"Creates an activity indicator view with the specified style.","type":"text"}],"role":"symbol","url":"\/documentation\/lphud\/contentview\/mode-swift.enum\/indicator(_:)-418k3","kind":"symbol","title":"indicator(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"indicator","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)ActivityIndicatorView","text":"ActivityIndicatorView","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"s:5LPHUD21ActivityIndicatorViewC5StyleO","text":"Style","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)ContentView","kind":"typeIdentifier","text":"ContentView"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD11ContentViewC4ModeO","text":"Mode"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView\/title","value":"ActivityIndicatorView","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView\/fragments","value":[{"kind":"identifier","text":"ActivityIndicatorView"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ContentView\/title","value":"ContentView"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ContentView\/fragments","value":[{"kind":"identifier","text":"ContentView"}],"op":"replace"}]}]}