{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"A flat bar progress view.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BarProgressView"}],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","symbolKind":"class","roleHeading":"Class","title":"BarProgressView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BarProgressView"}],"navigatorTitle":[{"text":"BarProgressView","kind":"identifier"}],"modules":[{"name":"LPHUD"}],"externalID":"c:@M@LPHUD@objc(cs)BarProgressView"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.LPHUD\/objc(cs)UIView"],"title":"Inherits From"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSCoding","doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSObject","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Progressive","doc:\/\/org.cocoapods.LPHUD\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.LPHUD\/s7CVarArgP","doc:\/\/org.cocoapods.LPHUD\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.LPHUD\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.LPHUD\/SQ","doc:\/\/org.cocoapods.LPHUD\/SH","doc:\/\/org.cocoapods.LPHUD\/s8SendableP","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.LPHUD\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIUserActivityRestoring"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/init()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/init(coder:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/init(frame:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/intrinsicContentSize","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/lineColor","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/progress","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/progressColor","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/progressRemainingColor"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/draw(_:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/barprogressview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/lphud\/barprogressview"]}],"references":{"doc://org.cocoapods.LPHUD/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItem"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BarProgressView":{"url":"\/documentation\/lphud\/barprogressview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BarProgressView","kind":"identifier"}],"abstract":[{"text":"A flat bar progress view.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView","navigatorTitle":[{"text":"BarProgressView","kind":"identifier"}],"role":"symbol","title":"BarProgressView","type":"topic"},"doc://org.cocoapods.LPHUD/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.LPHUD\/s7CVarArgP"},"doc://org.cocoapods.LPHUD/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.LPHUD/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.LPHUD\/s23CustomStringConvertibleP"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BarProgressView/progress":{"type":"topic","title":"progress","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/progress","url":"\/documentation\/lphud\/barprogressview\/progress","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"progress","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"kind":"symbol","abstract":[{"type":"text","text":"Progress (0.0 to 1.0)"}]},"doc://org.cocoapods.LPHUD/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSObject"},"doc://org.cocoapods.LPHUD/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSCoding"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BarProgressView/lineColor":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"lineColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"text":"Bar border line color. Defaults to white UIColor.white.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/lineColor","role":"symbol","title":"lineColor","url":"\/documentation\/lphud\/barprogressview\/linecolor"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BarProgressView/init(coder:)":{"title":"init(coder:)","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/lphud\/barprogressview\/init(coder:)","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/init(coder:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.LPHUD/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.LPHUD\/SQ"},"doc://org.cocoapods.LPHUD/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.LPHUD/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.LPHUD\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BarProgressView/progressRemainingColor":{"title":"progressRemainingColor","abstract":[{"text":"Bar background color. Defaults to clear UIColor.clear.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"progressRemainingColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"url":"\/documentation\/lphud\/barprogressview\/progressremainingcolor","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/progressRemainingColor","type":"topic","kind":"symbol","role":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.LPHUD/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s8SendableP"},"doc://org.cocoapods.LPHUD/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.LPHUD/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearance"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BarProgressView/init(frame:)":{"abstract":[],"url":"\/documentation\/lphud\/barprogressview\/init(frame:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/init(frame:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(frame:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Progressive":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Progressive","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/lphud\/progressive","navigatorTitle":[{"text":"Progressive","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Progressive","title":"Progressive"},"doc://org.cocoapods.LPHUD/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BarProgressView/init()":{"role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init()","abstract":[],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/init()","url":"\/documentation\/lphud\/barprogressview\/init()","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BarProgressView/intrinsicContentSize":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/intrinsicContentSize","abstract":[],"title":"intrinsicContentSize","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/lphud\/barprogressview\/intrinsiccontentsize"},"doc://org.cocoapods.LPHUD/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.LPHUD\/SH"},"doc://org.cocoapods.LPHUD/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.LPHUD\/5UIKit23UITraitChangeObservableP"},"doc://org.cocoapods.LPHUD/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.LPHUD/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BarProgressView/progressColor":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"progressColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Bar progress color. Defaults to white UIColor.white."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/progressColor","role":"symbol","title":"progressColor","url":"\/documentation\/lphud\/barprogressview\/progresscolor"},"doc://org.cocoapods.LPHUD/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(cs)UIView"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"type":"topic","url":"\/documentation\/lphud","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","abstract":[],"role":"collection","title":"LPHUD","kind":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.LPHUD/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.LPHUD/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BarProgressView/draw(_:)":{"role":"symbol","title":"draw(_:)","url":"\/documentation\/lphud\/barprogressview\/draw(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"draw"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}],"abstract":[],"navigatorTitle":[{"text":"drawRect:","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/draw(_:)"},"doc://org.cocoapods.LPHUD/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.LPHUD/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.LPHUD/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UICoordinateSpace","type":"unresolvable","title":"UIKit.UICoordinateSpace"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"BarProgressView","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"BarProgressView","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"BarProgressView"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/intrinsicContentSize"]},{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/draw(_:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/init()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/init(coder:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/init(frame:)"],"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/objc(cs)UIView"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BarProgressView","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BarProgressView\/title","value":"BarProgressView"},{"op":"replace","value":[{"text":"BarProgressView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BarProgressView\/fragments"},{"op":"replace","value":"initWithCoder:","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BarProgressView~1init(coder:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BarProgressView~1init(coder:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BarProgressView~1init(frame:)\/title","value":"initWithFrame:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BarProgressView~1init(frame:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}]},{"value":"init","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BarProgressView~1init()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BarProgressView~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BarProgressView~1intrinsicContentSize\/title","value":"intrinsicContentSize","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BarProgressView~1intrinsicContentSize\/fragments","value":[{"text":"intrinsicContentSize","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"drawRect:","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BarProgressView~1draw(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BarProgressView~1draw(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"drawRect:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}