{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"The natural size for the receiving view, considering only properties of the view itself."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView"]]},"variants":[{"paths":["\/documentation\/flyhud\/backgroundview\/intrinsiccontentsize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/flyhud\/backgroundview\/intrinsiccontentsize"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/intrinsicContentSize","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"FlyHUD"}],"roleHeading":"Instance Property","role":"symbol","title":"intrinsicContentSize","navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"externalID":"c:@M@FlyHUD@objc(cs)BackgroundView(py)intrinsicContentSize"},"references":{"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/BackgroundView/intrinsicContentSize":{"title":"intrinsicContentSize","url":"\/documentation\/flyhud\/backgroundview\/intrinsiccontentsize","role":"symbol","type":"topic","navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/intrinsicContentSize","abstract":[{"type":"text","text":"The natural size for the receiving view, considering only properties of the view itself."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"}],"kind":"symbol"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD":{"url":"\/documentation\/flyhud","role":"collection","kind":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","title":"FlyHUD","type":"topic","abstract":[]},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/BackgroundView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BackgroundView"}],"kind":"symbol","abstract":[{"text":"The view to use as the background of the HUD.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"HUD adds the background view as a subview behind all other views and uses its current frame location."}],"title":"BackgroundView","url":"\/documentation\/flyhud\/backgroundview","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BackgroundView"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"intrinsicContentSize","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"intrinsicContentSize"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BackgroundView~1intrinsicContentSize\/title","op":"replace","value":"intrinsicContentSize"},{"value":[{"text":"intrinsicContentSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BackgroundView~1intrinsicContentSize\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BackgroundView\/title","value":"BackgroundView"},{"value":[{"kind":"identifier","text":"BackgroundView"}],"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BackgroundView\/fragments","op":"replace"}]}]}