{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/bezelView","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"lazy"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bezelView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)BackgroundView","text":"BackgroundView","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"abstract":[{"text":"The view containing the labels and indicator (or customView).","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/hud\/bezelview"]}],"metadata":{"externalID":"s:5LPHUD3HUDC9bezelViewAA010BackgroundD0Cvp","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bezelView"},{"text":": ","kind":"text"},{"text":"BackgroundView","kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)BackgroundView"}],"role":"symbol","title":"bezelView","modules":[{"name":"LPHUD"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD"]]},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/BackgroundView":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BackgroundView"}],"navigatorTitle":[{"kind":"identifier","text":"BackgroundView"}],"url":"\/documentation\/lphud\/backgroundview","type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView","title":"BackgroundView"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/bezelView":{"abstract":[{"text":"The view containing the labels and indicator (or customView).","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bezelView","kind":"identifier"},{"kind":"text","text":": "},{"text":"BackgroundView","kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)BackgroundView"}],"title":"bezelView","url":"\/documentation\/lphud\/hud\/bezelview","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/bezelView","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"type":"topic","url":"\/documentation\/lphud","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","abstract":[],"role":"collection","title":"LPHUD","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD":{"url":"\/documentation\/lphud\/hud","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HUD"}],"abstract":[{"text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","navigatorTitle":[{"kind":"identifier","text":"HUD"}],"role":"symbol","title":"HUD","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView\/title","value":"BackgroundView"},{"value":[{"text":"BackgroundView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/title","value":"HUD"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/fragments","value":[{"text":"HUD","kind":"identifier"}]}]}]}