{"variants":[{"paths":["\/documentation\/lphud\/hud\/init(frame:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/lphud\/hud\/init(frame:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@LPHUD@objc(cs)HUD(im)initWithFrame:","modules":[{"name":"LPHUD"}],"symbolKind":"init","title":"init(frame:)","role":"symbol","roleHeading":"Initializer"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/init(frame:)"},"sections":[],"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD":{"url":"\/documentation\/lphud\/hud","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HUD"}],"abstract":[{"text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","navigatorTitle":[{"kind":"identifier","text":"HUD"}],"role":"symbol","title":"HUD","type":"topic"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/init(frame:)":{"abstract":[],"navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(frame:)","url":"\/documentation\/lphud\/hud\/init(frame:)","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/init(frame:)","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"type":"topic","url":"\/documentation\/lphud","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","abstract":[],"role":"collection","title":"LPHUD","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithFrame:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithFrame:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") "},{"text":"frame","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","value":"HUD","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/fragments","op":"replace","value":[{"kind":"identifier","text":"HUD"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD~1init(frame:)\/title","value":"initWithFrame:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD~1init(frame:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}