{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"intrinsicContentSize","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/intrinsicContentSize"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView"]]},"metadata":{"externalID":"c:@M@LPHUD@objc(cs)BarProgressView(py)intrinsicContentSize","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","title":"intrinsicContentSize","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"intrinsicContentSize"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"}],"modules":[{"name":"LPHUD"}],"navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/lphud\/barprogressview\/intrinsiccontentsize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/lphud\/barprogressview\/intrinsiccontentsize"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","url":"\/documentation\/lphud","kind":"symbol","title":"LPHUD","type":"topic","role":"collection","abstract":[]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BarProgressView/intrinsicContentSize":{"abstract":[],"title":"intrinsicContentSize","role":"symbol","url":"\/documentation\/lphud\/barprogressview\/intrinsiccontentsize","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/intrinsicContentSize","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"intrinsicContentSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BarProgressView":{"type":"topic","abstract":[{"type":"text","text":"A flat bar progress view."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView","url":"\/documentation\/lphud\/barprogressview","title":"BarProgressView","navigatorTitle":[{"text":"BarProgressView","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BarProgressView","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"intrinsicContentSize"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"intrinsicContentSize"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BarProgressView~1intrinsicContentSize\/title","value":"intrinsicContentSize"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BarProgressView~1intrinsicContentSize\/fragments","value":[{"text":"intrinsicContentSize","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BarProgressView\/title","op":"replace","value":"BarProgressView"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BarProgressView\/fragments","value":[{"text":"BarProgressView","kind":"identifier"}],"op":"replace"}]}]}