{"variants":[{"paths":["\/documentation\/lphud\/hud"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/lphud\/hud"]}],"topicSections":[{"title":"Structures","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/Animation-swift.struct","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/Layout-swift.struct"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/init(with:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/animation-swift.property","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/backgroundView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/completionBlock","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/contentView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/count","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/delegate","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/graceTime","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/isCountEnabled","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/isEventDeliveryEnabled","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/isHidden","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/keyboardGuide-swift.property","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/layout-swift.property","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/minShowTime","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/removeFromSuperViewOnHide"]},{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/commonInit()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/didMoveToSuperview()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/hide(animated:afterDelay:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/hide(using:afterDelay:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/hitTest(_:with:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/show(animated:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/show(using:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/keyboardGuide-swift.type.property"]},{"title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/hide(for:animated:afterDelay:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/hide(for:using:afterDelay:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/hideAll(for:animated:afterDelay:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/hideAll(for:using:afterDelay:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/huds(for:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/lastHUD(for:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/show(to:animated:mode:label:detailsLabel:populator:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/show(to:using:mode:label:detailsLabel:populator:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/showStatus(to:duration:animated:mode:label:offset:populator:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/showStatus(to:duration:using:mode:label:offset:populator:)"]},{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/KeyboardGuide-swift.enum"],"title":"Enumerations"},{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/KeyboardObservable-Implementations"],"generated":true,"title":"Default Implementations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD"},"metadata":{"title":"HUD","navigatorTitle":[{"text":"HUD","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"LPHUD"}],"roleHeading":"Class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HUD"}],"externalID":"c:@M@LPHUD@objc(cs)HUD"},"abstract":[{"text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView"]},{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSCoding","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/KeyboardObservable","doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSObject","doc:\/\/org.cocoapods.LPHUD\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.LPHUD\/s7CVarArgP","doc:\/\/org.cocoapods.LPHUD\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.LPHUD\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.LPHUD\/SQ","doc:\/\/org.cocoapods.LPHUD\/SH","doc:\/\/org.cocoapods.LPHUD\/s8SendableP","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.LPHUD\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HUD","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"style":"note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"To still allow touches to pass through the HUD, you can set hud.isEventDeliveryEnabled = true.","type":"text"}]}],"name":"Note"},{"style":"note","name":"Attention","type":"aside","content":[{"inlineContent":[{"text":"HUD is a UI class and should therefore only be accessed on the main thread.","type":"text"}],"type":"paragraph"}]}]}],"kind":"symbol","references":{"doc://org.cocoapods.LPHUD/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.LPHUD/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/layout-swift.property":{"url":"\/documentation\/lphud\/hud\/layout-swift.property","title":"layout","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"HUD layout configuration. eg: offset, margin, padding, etc."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layout","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD3HUDC6LayoutV","text":"Layout"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/layout-swift.property"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/hide(using:afterDelay:)":{"title":"hide(using:afterDelay:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hide"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"text":"Animation","kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD3HUDC9AnimationV"},{"text":"?, ","kind":"text"},{"text":"afterDelay","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/lphud\/hud\/hide(using:afterdelay:)","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/hide(using:afterDelay:)","abstract":[{"type":"text","text":"Hides the HUD. This still calls the "},{"type":"codeVoice","code":"hudWasHidden(:)"},{"text":" delegate. This is the counterpart of the show: method. Use it to hide the HUD when your task completes.","type":"text"}]},"doc://org.cocoapods.LPHUD/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification","type":"unresolvable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/hide(animated:afterDelay:)":{"url":"\/documentation\/lphud\/hud\/hide(animated:afterdelay:)","title":"hide(animated:afterDelay:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Hides the HUD. This still calls the "},{"code":"hudWasHidden(:)","type":"codeVoice"},{"type":"text","text":" delegate. This is the counterpart of the show: method. Use it to hide the HUD when your task completes."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hide"},{"kind":"text","text":"("},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"afterDelay","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/hide(animated:afterDelay:)"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD":{"title":"HUD","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HUD","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"HUD","kind":"identifier"}],"url":"\/documentation\/lphud\/hud","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","abstract":[{"type":"text","text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages."}],"role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/backgroundView":{"url":"\/documentation\/lphud\/hud\/backgroundview","title":"backgroundView","type":"topic","abstract":[{"text":"View covering the entire HUD area, placed behind contentView.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"backgroundView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)BackgroundView","text":"BackgroundView","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/backgroundView"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/animation-swift.property":{"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/animation-swift.property","url":"\/documentation\/lphud\/hud\/animation-swift.property","kind":"symbol","title":"animation","role":"symbol","abstract":[{"type":"text","text":"The animation (style, duration, damping) that should be used when the HUD is shown and hidden."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animation"},{"kind":"text","text":": "},{"text":"Animation","preciseIdentifier":"s:5LPHUD3HUDC9AnimationV","kind":"typeIdentifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/hide(for:animated:afterDelay:)":{"url":"\/documentation\/lphud\/hud\/hide(for:animated:afterdelay:)","title":"hide(for:animated:afterDelay:)","type":"topic","kind":"symbol","abstract":[{"text":"Finds the ","type":"text"},{"code":"top-most","type":"codeVoice"},{"text":" HUD subview that hasn’t finished and hides it. The counterpart to this method is ","type":"text"},{"type":"codeVoice","code":"show(to:using:...)"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hide"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"afterDelay","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/hide(for:animated:afterDelay:)"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/commonInit()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"commonInit"},{"text":"()","kind":"text"}],"url":"\/documentation\/lphud\/hud\/commoninit()","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/commonInit()","role":"symbol","title":"commonInit()","abstract":[{"text":"Common initialization method.","type":"text"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.LPHUD/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/contentView":{"url":"\/documentation\/lphud\/hud\/contentview","title":"contentView","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The view containing the labels, button and indicator (or customView). The HUD object places the content in this view in front of any background views."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ContentView","kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)ContentView"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/contentView"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/removeFromSuperViewOnHide":{"url":"\/documentation\/lphud\/hud\/removefromsuperviewonhide","title":"removeFromSuperViewOnHide","type":"topic","abstract":[{"type":"text","text":"Removes the HUD from its parent view when hidden. "},{"type":"codeVoice","code":"Defaults to true"},{"type":"text","text":"."}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeFromSuperViewOnHide","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/removeFromSuperViewOnHide"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/keyboardGuide-swift.type.property":{"url":"\/documentation\/lphud\/hud\/keyboardguide-swift.type.property","title":"keyboardGuide","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A layout guide that tracks the keyboard’s position in your app’s layout. "},{"type":"codeVoice","code":"Default to disable"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardGuide","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD3HUDC13KeyboardGuideO","text":"KeyboardGuide"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/keyboardGuide-swift.type.property"},"doc://org.cocoapods.LPHUD/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/init(with:)":{"url":"\/documentation\/lphud\/hud\/init(with:)","title":"init(with:)","type":"topic","kind":"symbol","abstract":[{"text":"A convenience constructor that initializes the HUD with the ","type":"text"},{"type":"codeVoice","code":"view's bounds"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"Calls the designated constructor with "},{"code":"view.bounds","type":"codeVoice"},{"type":"text","text":" as the parameter."}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/init(with:)"},"doc://org.cocoapods.LPHUD/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/didMoveToSuperview()":{"url":"\/documentation\/lphud\/hud\/didmovetosuperview()","title":"didMoveToSuperview()","type":"topic","kind":"symbol","abstract":[{"text":"Tells the view that its superview changed.","type":"text"}],"navigatorTitle":[{"text":"didMoveToSuperview","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didMoveToSuperview","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/didMoveToSuperview()"},"doc://org.cocoapods.LPHUD/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.LPHUD/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"role":"collection","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","type":"topic","kind":"symbol","title":"LPHUD","abstract":[],"url":"\/documentation\/lphud"},"doc://org.cocoapods.LPHUD/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/initWithFrame:":{"url":"\/documentation\/lphud\/hud\/initwithframe:","title":"initWithFrame:","type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrame:"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/initWithFrame:"},"doc://org.cocoapods.LPHUD/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s8SendableP","title":"Swift.Sendable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/initWithCoder:":{"url":"\/documentation\/lphud\/hud\/initwithcoder:","title":"initWithCoder:","type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/initWithCoder:"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/showStatus(to:duration:using:mode:label:offset:populator:)":{"url":"\/documentation\/lphud\/hud\/showstatus(to:duration:using:mode:label:offset:populator:)","title":"showStatus(to:duration:using:mode:label:offset:populator:)","type":"topic","abstract":[{"type":"text","text":"Creates a new HUD. adds it to provided view and shows it. And auto hides the HUD after a duration."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showStatus","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"duration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"using"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD3HUDC9AnimationV","text":"Animation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"text":"ContentView","preciseIdentifier":"c:@M@LPHUD@objc(cs)ContentView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:5LPHUD11ContentViewC4ModeO","text":"Mode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"label","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"populator","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD","kind":"typeIdentifier","text":"HUD"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?) -> ","kind":"text"},{"text":"HUD","kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/showStatus(to:duration:using:mode:label:offset:populator:)"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BaseView":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BaseView","kind":"identifier"}],"kind":"symbol","title":"BaseView","url":"\/documentation\/lphud\/baseview","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView","abstract":[{"type":"text","text":"A base view only provides one "},{"type":"codeVoice","code":"commonInit"},{"type":"text","text":" method."}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseView"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/Layout-swift.struct":{"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/Layout-swift.struct","url":"\/documentation\/lphud\/hud\/layout-swift.struct","navigatorTitle":[{"kind":"identifier","text":"Layout"}],"title":"HUD.Layout","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Layout","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/huds(for:)":{"title":"huds(for:)","abstract":[{"type":"text","text":"Find all unfinished HUD subviews and return them."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/huds(for:)","url":"\/documentation\/lphud\/hud\/huds(for:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"huds"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"text":"HUD","kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD"},{"text":"]","kind":"text"}]},"doc://org.cocoapods.LPHUD/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/show(to:using:mode:label:detailsLabel:populator:)":{"url":"\/documentation\/lphud\/hud\/show(to:using:mode:label:detailslabel:populator:)","title":"show(to:using:mode:label:detailsLabel:populator:)","type":"topic","abstract":[{"text":"Creates a new HUD. adds it to provided view and shows it. The counterpart to this method is ","type":"text"},{"code":"hide(for:using:)","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"show","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":", ","kind":"text"},{"text":"using","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Animation","preciseIdentifier":"s:5LPHUD3HUDC9AnimationV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"mode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)ContentView","text":"ContentView"},{"kind":"text","text":"."},{"preciseIdentifier":"s:5LPHUD11ContentViewC4ModeO","kind":"typeIdentifier","text":"Mode"},{"kind":"text","text":", "},{"text":"label","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"detailsLabel"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"populator","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"HUD","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD","kind":"typeIdentifier","text":"HUD"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/show(to:using:mode:label:detailsLabel:populator:)"},"doc://org.cocoapods.LPHUD/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUDExtended":{"kind":"symbol","abstract":[{"type":"text","text":"Protocol describing the "},{"type":"codeVoice","code":"h"},{"text":" extension points for HUD extended types.","type":"text"}],"type":"topic","url":"\/documentation\/lphud\/hudextended","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HUDExtended","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended","title":"HUDExtended","navigatorTitle":[{"kind":"identifier","text":"HUDExtended"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/hideAll(for:animated:afterDelay:)":{"url":"\/documentation\/lphud\/hud\/hideall(for:animated:afterdelay:)","title":"hideAll(for:animated:afterDelay:)","type":"topic","abstract":[{"type":"text","text":"Find all unfinished HUD subviews and hide them. The counterpart to this method is "},{"code":"show(to:using:...)","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hideAll"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"afterDelay"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/hideAll(for:animated:afterDelay:)"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/show(using:)":{"url":"\/documentation\/lphud\/hud\/show(using:)","title":"show(using:)","type":"topic","abstract":[{"type":"text","text":"Displays the HUD."}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"show","kind":"identifier"},{"kind":"text","text":"("},{"text":"using","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Animation","preciseIdentifier":"s:5LPHUD3HUDC9AnimationV"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/show(using:)"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/graceTime":{"url":"\/documentation\/lphud\/hud\/gracetime","title":"graceTime","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Grace period is the time (in seconds) that the invoked method may be run without showing the HUD."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"graceTime","kind":"identifier"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/graceTime"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/isHidden":{"url":"\/documentation\/lphud\/hud\/ishidden","title":"isHidden","type":"topic","abstract":[{"type":"text","text":"A Boolean value that determines whether the view is hidden."}],"kind":"symbol","navigatorTitle":[{"text":"hidden","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isHidden","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/isHidden"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/delegate":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/delegate","abstract":[{"type":"text","text":"The HUD delegate object. Receives HUD state notifications."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": ","kind":"text"},{"text":"HUDDelegate","kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD11HUDDelegateP"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/lphud\/hud\/delegate","title":"delegate"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/isEventDeliveryEnabled":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isEventDeliveryEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isEventDeliveryEnabled","url":"\/documentation\/lphud\/hud\/iseventdeliveryenabled","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/isEventDeliveryEnabled","abstract":[{"text":"A Boolean value that controls the delivery of user events. ","type":"text"},{"type":"codeVoice","code":"Defaults to false"},{"text":".","type":"text"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSCoding"},"doc://org.cocoapods.LPHUD/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.LPHUD\/5UIKit23UITraitChangeObservableP"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/lastHUD(for:)":{"url":"\/documentation\/lphud\/hud\/lasthud(for:)","title":"lastHUD(for:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Finds the "},{"type":"codeVoice","code":"top-most"},{"text":" HUD subview that hasn’t finished and returns it.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lastHUD","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD","text":"HUD"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/lastHUD(for:)"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/KeyboardObservable-Implementations":{"url":"\/documentation\/lphud\/hud\/keyboardobservable-implementations","title":"KeyboardObservable Implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/KeyboardObservable-Implementations","abstract":[],"kind":"article"},"doc://org.cocoapods.LPHUD/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.LPHUD\/SH"},"doc://org.cocoapods.LPHUD/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.LPHUD/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/hideAll(for:using:afterDelay:)":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/hideAll(for:using:afterDelay:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hideAll","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"using","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Animation","kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD3HUDC9AnimationV"},{"text":"?, ","kind":"text"},{"text":"afterDelay","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/lphud\/hud\/hideall(for:using:afterdelay:)","title":"hideAll(for:using:afterDelay:)","abstract":[{"text":"Find all unfinished HUD subviews and hide them. The counterpart to this method is ","type":"text"},{"type":"codeVoice","code":"show(to:using:...)"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","type":"topic"},"doc://org.cocoapods.LPHUD/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItem"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/minShowTime":{"title":"minShowTime","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"minShowTime","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"kind":"symbol","url":"\/documentation\/lphud\/hud\/minshowtime","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/minShowTime","abstract":[{"type":"text","text":"The minimum time (in seconds) that the HUD is shown. This avoids the problem of the HUD being shown and than instantly hidden."}]},"doc://org.cocoapods.LPHUD/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s7CVarArgP"},"doc://org.cocoapods.LPHUD/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearance"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/isCountEnabled":{"url":"\/documentation\/lphud\/hud\/iscountenabled","title":"isCountEnabled","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A Boolean value indicating whether the HUD is in the enable activity count. "},{"type":"codeVoice","code":"Defaults to false"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isCountEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/isCountEnabled"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/show(animated:)":{"kind":"symbol","role":"symbol","url":"\/documentation\/lphud\/hud\/show(animated:)","abstract":[{"type":"text","text":"Displays the HUD."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/show(animated:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"show","kind":"identifier"},{"text":"(","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"show(animated:)","type":"topic"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/showStatus(to:duration:animated:mode:label:offset:populator:)":{"role":"symbol","abstract":[{"text":"Creates a new HUD. adds it to provided view and shows it. And auto hides the HUD after a duration.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/showStatus(to:duration:animated:mode:label:offset:populator:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"showStatus"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"duration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"mode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)ContentView","text":"ContentView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:5LPHUD11ContentViewC4ModeO","kind":"typeIdentifier","text":"Mode"},{"kind":"text","text":", "},{"text":"label","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"offset"},{"kind":"text","text":": "},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"populator"},{"text":": ((","kind":"text"},{"text":"HUD","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD","kind":"typeIdentifier","text":"HUD"}],"type":"topic","title":"showStatus(to:duration:animated:mode:label:offset:populator:)","kind":"symbol","url":"\/documentation\/lphud\/hud\/showstatus(to:duration:animated:mode:label:offset:populator:)"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/KeyboardObservable":{"abstract":[{"text":"A keyboard observer that tracks the keyboard’s position in your app’s layout.","type":"text"}],"url":"\/documentation\/lphud\/keyboardobservable","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"KeyboardObservable","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"KeyboardObservable","kind":"identifier"}],"title":"KeyboardObservable","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/KeyboardObservable"},"doc://org.cocoapods.LPHUD/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.LPHUD\/s23CustomStringConvertibleP"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/count":{"url":"\/documentation\/lphud\/hud\/count","title":"count","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"This is an activity count that records multiple shows and hides of the same HUD object."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"count"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/count"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/KeyboardGuide-swift.enum":{"title":"HUD.KeyboardGuide","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/KeyboardGuide-swift.enum","role":"symbol","url":"\/documentation\/lphud\/hud\/keyboardguide-swift.enum","abstract":[{"text":"A layout guide that tracks the keyboard’s position in your app’s layout.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"KeyboardGuide","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardGuide"}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/hide(for:using:afterDelay:)":{"url":"\/documentation\/lphud\/hud\/hide(for:using:afterdelay:)","title":"hide(for:using:afterDelay:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Finds the "},{"code":"top-most","type":"codeVoice"},{"type":"text","text":" HUD subview that hasn’t finished and hides it. The counterpart to this method is "},{"type":"codeVoice","code":"show(to:using:...)"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"hide","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"text":"using","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Animation","preciseIdentifier":"s:5LPHUD3HUDC9AnimationV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"afterDelay","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/hide(for:using:afterDelay:)"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/show(to:animated:mode:label:detailsLabel:populator:)":{"role":"symbol","type":"topic","title":"show(to:animated:mode:label:detailsLabel:populator:)","abstract":[{"type":"text","text":"Creates a new HUD. adds it to provided view and shows it. The counterpart to this method is "},{"code":"hide(for:using:)","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/show(to:animated:mode:label:detailsLabel:populator:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"text":", ","kind":"text"},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"mode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)ContentView","text":"ContentView"},{"kind":"text","text":"."},{"text":"Mode","kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD11ContentViewC4ModeO"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"label"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"detailsLabel"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"populator","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"HUD","kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?) -> ","kind":"text"},{"text":"HUD","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD","kind":"typeIdentifier"}],"url":"\/documentation\/lphud\/hud\/show(to:animated:mode:label:detailslabel:populator:)","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/keyboardGuide-swift.property":{"url":"\/documentation\/lphud\/hud\/keyboardguide-swift.property","title":"keyboardGuide","type":"topic","abstract":[{"text":"A layout guide that tracks the keyboard’s position in your app’s layout. ","type":"text"},{"code":"Default to nil","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardGuide","kind":"identifier"},{"text":": ","kind":"text"},{"text":"KeyboardGuide","preciseIdentifier":"s:5LPHUD3HUDC13KeyboardGuideO","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/keyboardGuide-swift.property"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/Animation-swift.struct":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/Animation-swift.struct","navigatorTitle":[{"text":"Animation","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Animation","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"HUD.Animation","url":"\/documentation\/lphud\/hud\/animation-swift.struct","abstract":[]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/completionBlock":{"url":"\/documentation\/lphud\/hud\/completionblock","title":"completionBlock","type":"topic","kind":"symbol","abstract":[{"text":"Called after the HUD was fully hidden from the screen.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"completionBlock","kind":"identifier"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"hud","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD","kind":"typeIdentifier","text":"HUD"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/completionBlock"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/hitTest(_:with:)":{"navigatorTitle":[{"kind":"identifier","text":"hitTest:withEvent:"}],"kind":"symbol","abstract":[{"type":"text","text":"Returns the farthest descendant in the view hierarchy of the current view, including itself, that contains the specified point."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/hitTest(_:with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hitTest","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":", "},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"text":"?) -> ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?","kind":"text"}],"url":"\/documentation\/lphud\/hud\/hittest(_:with:)","title":"hitTest(_:with:)","type":"topic"},"doc://org.cocoapods.LPHUD/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HUD"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"HUD","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"HUD","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/isHidden"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/didMoveToSuperview()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/hitTest(_:with:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/initWithCoder:","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/initWithFrame:"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HUD"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView","kind":"typeIdentifier","text":"BaseView","preciseIdentifier":"c:@M@LPHUD@objc(cs)BaseView"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"HUD","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/fragments","value":[{"kind":"identifier","text":"HUD"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD~1didMoveToSuperview()\/title","value":"didMoveToSuperview"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD~1didMoveToSuperview()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didMoveToSuperview","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BaseView\/title","value":"BaseView","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BaseView\/fragments","op":"replace","value":[{"kind":"identifier","text":"BaseView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD~1isHidden\/title","value":"hidden"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD~1isHidden\/fragments","value":[{"text":"hidden","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD~1hitTest(_:with:)\/title","op":"replace","value":"hitTest:withEvent:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD~1hitTest(_:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hitTest:withEvent:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}