{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Conforming Types","type":"conformingTypes","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/Style-swift.enum","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Swift\/Bool","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/CoreFoundation\/CGFloat","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/CoreFoundation\/CGPoint","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/CoreFoundation\/CGRect","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/IndicatorPosition-swift.enum","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Layout-swift.struct","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Mode-swift.enum","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Swift\/Float","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/Animation-swift.struct","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/KeyboardGuide-swift.enum","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/Layout-swift.struct","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ObjectiveC\/NSObject","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Swift\/Optional","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedCorners","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/UIKit\/UIActivityIndicatorView\/Style"]}],"metadata":{"roleHeading":"Protocol","externalID":"s:5LPHUD11HUDExtendedP","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HUDExtended"}],"symbolKind":"protocol","modules":[{"name":"LPHUD"}],"navigatorTitle":[{"text":"HUDExtended","kind":"identifier"}],"role":"symbol","title":"HUDExtended"},"variants":[{"paths":["\/documentation\/lphud\/hudextended"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"title":"Associated Types","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended\/ExtendedType"]},{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended\/h-8ucl"],"title":"Instance Properties"},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended\/h-637gh"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HUDExtended","kind":"identifier"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Protocol describing the "},{"type":"codeVoice","code":"h"},{"type":"text","text":" extension points for HUD extended types."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/BackgroundView":{"kind":"symbol","abstract":[{"type":"text","text":"The view to use as the background of the HUD."},{"text":" ","type":"text"},{"text":"HUD adds the background view as a subview behind all other views and uses its current frame location.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BackgroundView","kind":"identifier"}],"title":"BackgroundView","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView","role":"symbol","navigatorTitle":[{"text":"BackgroundView","kind":"identifier"}],"url":"\/documentation\/lphud\/backgroundview"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Swift/Float":{"fragments":[{"kind":"keyword","text":"extension"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Float","preciseIdentifier":"s:Sf"}],"navigatorTitle":[{"kind":"identifier","text":"Float"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Swift\/Float","url":"\/documentation\/lphud\/swift\/float","role":"symbol","title":"Float","type":"topic","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/Mode-swift.enum":{"title":"ContentView.Mode","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Mode-swift.enum","abstract":[],"role":"symbol","navigatorTitle":[{"text":"Mode","kind":"identifier"}],"url":"\/documentation\/lphud\/contentview\/mode-swift.enum","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Mode","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ObjectiveC/NSObject":{"type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSObject","kind":"identifier","preciseIdentifier":"c:objc(cs)NSObject"}],"url":"\/documentation\/lphud\/objectivec\/nsobject","navigatorTitle":[{"text":"NSObject","kind":"identifier"}],"title":"NSObject","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ObjectiveC\/NSObject","role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/CoreFoundation/CGFloat":{"navigatorTitle":[{"kind":"identifier","text":"CGFloat"}],"url":"\/documentation\/lphud\/corefoundation\/cgfloat","type":"topic","title":"CGFloat","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/CoreFoundation\/CGFloat","abstract":[],"kind":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CGFloat","kind":"identifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"role":"collection","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","type":"topic","kind":"symbol","title":"LPHUD","abstract":[],"url":"\/documentation\/lphud"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/UIKit/UIActivityIndicatorView/Style":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/UIKit\/UIActivityIndicatorView\/Style","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Style"}],"abstract":[],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIActivityIndicatorView","kind":"identifier","text":"UIActivityIndicatorView"},{"text":".","kind":"text"},{"text":"Style","kind":"identifier","preciseIdentifier":"c:@E@UIActivityIndicatorViewStyle"}],"title":"UIActivityIndicatorView.Style","url":"\/documentation\/lphud\/uikit\/uiactivityindicatorview\/style","type":"topic"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUDExtended/h-637gh":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended\/h-637gh","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"h"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5LPHUD12HUDExtensionV","text":"HUDExtension","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD11HUDExtendedP12ExtendedTypeQa","text":"ExtendedType"},{"text":">.Type","kind":"text"}],"role":"symbol","title":"h","abstract":[{"type":"text","text":"Static HUD extension point."}],"kind":"symbol","required":true,"defaultImplementations":2,"url":"\/documentation\/lphud\/hudextended\/h-637gh"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button":{"url":"\/documentation\/lphud\/button","type":"topic","title":"Button","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Button"}],"navigatorTitle":[{"kind":"identifier","text":"Button"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUDExtended/h-8ucl":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended\/h-8ucl","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"h"},{"kind":"text","text":": "},{"text":"HUDExtension","kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD12HUDExtensionV"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:5LPHUD11HUDExtendedP12ExtendedTypeQa","kind":"typeIdentifier","text":"ExtendedType"},{"text":">","kind":"text"}],"role":"symbol","title":"h","abstract":[{"type":"text","text":"Instance HUD extension point."}],"kind":"symbol","required":true,"defaultImplementations":2,"url":"\/documentation\/lphud\/hudextended\/h-8ucl"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BaseView":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BaseView","kind":"identifier"}],"kind":"symbol","title":"BaseView","url":"\/documentation\/lphud\/baseview","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView","abstract":[{"type":"text","text":"A base view only provides one "},{"type":"codeVoice","code":"commonInit"},{"type":"text","text":" method."}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseView"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContentView"}],"type":"topic","navigatorTitle":[{"text":"ContentView","kind":"identifier"}],"abstract":[{"text":"The content view of the HUD object. The view containing the labels, button and indicator (or customView).","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The HUD object places the content in this view in front of any background views."}],"kind":"symbol","role":"symbol","url":"\/documentation\/lphud\/contentview","title":"ContentView"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Swift/Optional":{"kind":"symbol","type":"topic","url":"\/documentation\/lphud\/swift\/optional","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"Optional","preciseIdentifier":"s:Sq"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Swift\/Optional","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Optional"}],"title":"Optional"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/Animation-swift.struct":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/Animation-swift.struct","navigatorTitle":[{"text":"Animation","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Animation","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"HUD.Animation","url":"\/documentation\/lphud\/hud\/animation-swift.struct","abstract":[]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BackgroundView/Style-swift.enum":{"navigatorTitle":[{"kind":"identifier","text":"Style"}],"abstract":[],"type":"topic","url":"\/documentation\/lphud\/backgroundview\/style-swift.enum","kind":"symbol","title":"BackgroundView.Style","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/Style-swift.enum","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUDExtended/ExtendedType":{"type":"topic","url":"\/documentation\/lphud\/hudextended\/extendedtype","title":"ExtendedType","role":"symbol","fragments":[{"text":"associatedtype","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ExtendedType","kind":"identifier"}],"kind":"symbol","required":true,"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended\/ExtendedType","abstract":[{"type":"text","text":"Type being extended."}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Swift/Bool":{"navigatorTitle":[{"kind":"identifier","text":"Bool"}],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Swift\/Bool","role":"symbol","kind":"symbol","title":"Bool","type":"topic","url":"\/documentation\/lphud\/swift\/bool"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/Layout-swift.struct":{"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/Layout-swift.struct","url":"\/documentation\/lphud\/hud\/layout-swift.struct","navigatorTitle":[{"kind":"identifier","text":"Layout"}],"title":"HUD.Layout","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Layout","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ProgressView","kind":"identifier"}],"navigatorTitle":[{"text":"ProgressView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/lphud\/progressview","abstract":[{"text":"A view that depicts the progress of a task over time.","type":"text"}],"title":"ProgressView"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundedCorners":{"navigatorTitle":[{"kind":"identifier","text":"RoundedCorners"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedCorners","title":"RoundedCorners","abstract":[],"url":"\/documentation\/lphud\/roundedcorners","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"RoundedCorners","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/CoreFoundation/CGRect":{"kind":"symbol","title":"CGRect","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CGRect"}],"url":"\/documentation\/lphud\/corefoundation\/cgrect","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/CoreFoundation\/CGRect","abstract":[],"role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/CoreFoundation/CGPoint":{"navigatorTitle":[{"kind":"identifier","text":"CGPoint"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/CoreFoundation\/CGPoint","abstract":[],"url":"\/documentation\/lphud\/corefoundation\/cgpoint","kind":"symbol","title":"CGPoint"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD":{"title":"HUD","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HUD","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"HUD","kind":"identifier"}],"url":"\/documentation\/lphud\/hud","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","abstract":[{"type":"text","text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages."}],"role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/Layout-swift.struct":{"abstract":[],"title":"ContentView.Layout","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Layout","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Layout-swift.struct","url":"\/documentation\/lphud\/contentview\/layout-swift.struct","kind":"symbol","navigatorTitle":[{"text":"Layout","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView":{"url":"\/documentation\/lphud\/activityindicatorview","navigatorTitle":[{"text":"ActivityIndicatorView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ActivityIndicatorView","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"ActivityIndicatorView","abstract":[{"type":"text","text":"A view that shows that a task is in progress."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/KeyboardGuide-swift.enum":{"title":"HUD.KeyboardGuide","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/KeyboardGuide-swift.enum","role":"symbol","url":"\/documentation\/lphud\/hud\/keyboardguide-swift.enum","abstract":[{"text":"A layout guide that tracks the keyboard’s position in your app’s layout.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"KeyboardGuide","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardGuide"}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/IndicatorPosition-swift.enum":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndicatorPosition","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/IndicatorPosition-swift.enum","url":"\/documentation\/lphud\/contentview\/indicatorposition-swift.enum","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IndicatorPosition"}],"title":"ContentView.IndicatorPosition","abstract":[],"kind":"symbol","type":"topic"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Label":{"url":"\/documentation\/lphud\/label","kind":"symbol","title":"Label","abstract":[{"type":"text","text":"A view that displays one or more lines of informational text."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label","navigatorTitle":[{"kind":"identifier","text":"Label"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Label"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUDExtended":{"kind":"symbol","abstract":[{"type":"text","text":"Protocol describing the "},{"type":"codeVoice","code":"h"},{"text":" extension points for HUD extended types.","type":"text"}],"type":"topic","url":"\/documentation\/lphud\/hudextended","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HUDExtended","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended","title":"HUDExtended","navigatorTitle":[{"kind":"identifier","text":"HUDExtended"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView\/title","op":"replace","value":"BackgroundView"},{"op":"replace","value":[{"text":"BackgroundView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView\/fragments"},{"op":"replace","value":"Button","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button\/fragments","value":[{"kind":"identifier","text":"Button"}]},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BaseView\/title","value":"BaseView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BaseView\/fragments","value":[{"text":"BaseView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ContentView\/title","op":"replace","value":"ContentView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ContentView\/fragments","value":[{"kind":"identifier","text":"ContentView"}]},{"op":"replace","value":"ProgressView","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ProgressView"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/title","value":"HUD"},{"value":[{"text":"HUD","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/fragments","op":"replace"},{"value":"ActivityIndicatorView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView\/fragments","value":[{"text":"ActivityIndicatorView","kind":"identifier"}]},{"value":"Label","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Label\/title","op":"replace"},{"value":[{"text":"Label","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Label\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}