{"variants":[{"paths":["\/documentation\/lphud\/progressive"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Progressive"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"s:5LPHUD11ProgressiveP","title":"Progressive","symbolKind":"protocol","navigatorTitle":[{"text":"Progressive","kind":"identifier"}],"roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"Progressive","kind":"identifier"}],"modules":[{"name":"LPHUD"}],"role":"symbol"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Progressive\/progress"],"title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Progressive","kind":"identifier"},{"kind":"text","text":" : AnyObject"}]}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView"],"type":"conformingTypes","title":"Conforming Types"}],"sections":[],"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView":{"kind":"symbol","abstract":[],"role":"symbol","title":"ProgressView","url":"\/documentation\/lphud\/progressview","navigatorTitle":[{"text":"ProgressView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ProgressView"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Progressive/progress":{"role":"symbol","title":"progress","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"progress","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"url":"\/documentation\/lphud\/progressive\/progress","abstract":[],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Progressive\/progress","kind":"symbol","type":"topic","required":true},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Progressive":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Progressive","navigatorTitle":[{"kind":"identifier","text":"Progressive"}],"abstract":[],"url":"\/documentation\/lphud\/progressive","role":"symbol","title":"Progressive","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Progressive","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","url":"\/documentation\/lphud","kind":"symbol","title":"LPHUD","type":"topic","role":"collection","abstract":[]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundProgressView":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView","role":"symbol","url":"\/documentation\/lphud\/roundprogressview","type":"topic","abstract":[{"text":"A progress view for showing definite progress by filling up a circle (pie chart).","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RoundProgressView","kind":"identifier"}],"title":"RoundProgressView","navigatorTitle":[{"kind":"identifier","text":"RoundProgressView"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BarProgressView":{"type":"topic","abstract":[{"type":"text","text":"A flat bar progress view."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView","url":"\/documentation\/lphud\/barprogressview","title":"BarProgressView","navigatorTitle":[{"text":"BarProgressView","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BarProgressView","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/title","value":"ProgressView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/fragments","value":[{"kind":"identifier","text":"ProgressView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView\/title","value":"RoundProgressView"},{"value":[{"text":"RoundProgressView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BarProgressView\/title","value":"BarProgressView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BarProgressView\/fragments","value":[{"text":"BarProgressView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}