{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"intrinsicContentSize","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/intrinsicContentSize","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"LPHUD"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"externalID":"c:@M@LPHUD@objc(cs)ActivityIndicatorView(py)intrinsicContentSize","symbolKind":"property","role":"symbol","title":"intrinsicContentSize"},"sections":[],"abstract":[{"text":"The natural size for the receiving view, considering only properties of the view itself.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/activityindicatorview\/intrinsiccontentsize"]},{"paths":["\/documentation\/lphud\/activityindicatorview\/intrinsiccontentsize"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"role":"collection","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","type":"topic","kind":"symbol","title":"LPHUD","abstract":[],"url":"\/documentation\/lphud"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView":{"url":"\/documentation\/lphud\/activityindicatorview","navigatorTitle":[{"text":"ActivityIndicatorView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ActivityIndicatorView","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"ActivityIndicatorView","abstract":[{"type":"text","text":"A view that shows that a task is in progress."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView/intrinsicContentSize":{"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/intrinsicContentSize","title":"intrinsicContentSize","kind":"symbol","url":"\/documentation\/lphud\/activityindicatorview\/intrinsiccontentsize","abstract":[{"text":"The natural size for the receiving view, considering only properties of the view itself.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"intrinsicContentSize","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"intrinsicContentSize","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"text":" ","kind":"text"},{"kind":"identifier","text":"intrinsicContentSize"}]}]}},{"value":"ActivityIndicatorView","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ActivityIndicatorView"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView\/fragments","op":"replace"},{"value":"intrinsicContentSize","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView~1intrinsicContentSize\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView~1intrinsicContentSize\/fragments","op":"replace","value":[{"kind":"identifier","text":"intrinsicContentSize"}]}]}]}