{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/lphud\/activityindicatorview\/didmovetowindow()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/lphud\/activityindicatorview\/didmovetowindow()"]}],"kind":"symbol","metadata":{"modules":[{"name":"LPHUD"}],"externalID":"c:@M@LPHUD@objc(cs)ActivityIndicatorView(im)didMoveToWindow","navigatorTitle":[{"text":"didMoveToWindow","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"},{"text":"()","kind":"text"}],"title":"didMoveToWindow()"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/didMoveToWindow()"},"abstract":[{"type":"text","text":"Tells the view that its window object changed."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView"]]},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView/didMoveToWindow()":{"title":"didMoveToWindow()","url":"\/documentation\/lphud\/activityindicatorview\/didmovetowindow()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didMoveToWindow"},{"text":"()","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/didMoveToWindow()","abstract":[{"type":"text","text":"Tells the view that its window object changed."}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"didMoveToWindow","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView":{"abstract":[{"text":"A view that shows that a task is in progress.","type":"text"}],"navigatorTitle":[{"text":"ActivityIndicatorView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivityIndicatorView"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView","title":"ActivityIndicatorView","kind":"symbol","url":"\/documentation\/lphud\/activityindicatorview","type":"topic","role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"abstract":[],"role":"collection","kind":"symbol","type":"topic","title":"LPHUD","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","url":"\/documentation\/lphud"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"didMoveToWindow","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"didMoveToWindow","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView~1didMoveToWindow()\/title","value":"didMoveToWindow","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView~1didMoveToWindow()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"didMoveToWindow","kind":"identifier"}]},{"op":"replace","value":"ActivityIndicatorView","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView\/title"},{"op":"replace","value":[{"text":"ActivityIndicatorView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}