{"abstract":[{"text":"The natural size for the receiving view, considering only properties of the view itself.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"intrinsicContentSize","symbolKind":"property","modules":[{"name":"LPHUD"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}],"role":"symbol","externalID":"c:@M@LPHUD@objc(cs)Label(py)intrinsicContentSize","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label\/intrinsicContentSize","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/label\/intrinsiccontentsize"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/lphud\/label\/intrinsiccontentsize"]}],"sections":[],"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/Label":{"navigatorTitle":[{"text":"Label","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label","abstract":[{"text":"A view that displays one or more lines of informational text.","type":"text"}],"title":"Label","kind":"symbol","url":"\/documentation\/lphud\/label","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Label"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"abstract":[],"role":"collection","kind":"symbol","type":"topic","title":"LPHUD","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","url":"\/documentation\/lphud"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Label/intrinsicContentSize":{"navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}],"abstract":[{"type":"text","text":"The natural size for the receiving view, considering only properties of the view itself."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label\/intrinsicContentSize","type":"topic","kind":"symbol","title":"intrinsicContentSize","url":"\/documentation\/lphud\/label\/intrinsiccontentsize","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"intrinsicContentSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"intrinsicContentSize","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"intrinsicContentSize","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Label\/title","op":"replace","value":"Label"},{"value":[{"text":"Label","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Label\/fragments","op":"replace"},{"value":"intrinsicContentSize","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Label~1intrinsicContentSize\/title"},{"value":[{"text":"intrinsicContentSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Label~1intrinsicContentSize\/fragments"}]}]}