{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"Lays out subviews.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/layoutSubviews()"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/button\/layoutsubviews()"]},{"paths":["\/documentation\/lphud\/button\/layoutsubviews()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"symbolKind":"method","role":"symbol","title":"layoutSubviews()","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@LPHUD@objc(cs)Button(im)layoutSubviews","modules":[{"name":"LPHUD"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button"]]},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button":{"kind":"symbol","url":"\/documentation\/lphud\/button","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button","title":"Button","role":"symbol","abstract":[{"type":"text","text":"A control that executes your custom code in response to user interactions."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Button","kind":"identifier"}],"navigatorTitle":[{"text":"Button","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button/layoutSubviews()":{"url":"\/documentation\/lphud\/button\/layoutsubviews()","role":"symbol","type":"topic","title":"layoutSubviews()","abstract":[{"type":"text","text":"Lays out subviews."}],"kind":"symbol","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"abstract":[],"role":"collection","kind":"symbol","type":"topic","title":"LPHUD","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","url":"\/documentation\/lphud"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"layoutSubviews","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button\/title","value":"Button","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button\/fragments","op":"replace","value":[{"kind":"identifier","text":"Button"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1layoutSubviews()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}]}]}]}