{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button","interfaceLanguage":"swift"},"abstract":[{"text":"A control that executes your custom code in response to user interactions.","type":"text"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.LPHUD\/objc(cs)UIButton"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSCoding","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended","doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSObject","doc:\/\/org.cocoapods.LPHUD\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.LPHUD\/s7CVarArgP","doc:\/\/org.cocoapods.LPHUD\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.LPHUD\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.LPHUD\/SQ","doc:\/\/org.cocoapods.LPHUD\/SH","doc:\/\/org.cocoapods.LPHUD\/s8SendableP","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIContextMenuInteractionDelegate","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UISpringLoadedInteractionSupporting","doc:\/\/org.cocoapods.LPHUD\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","type":"conformsTo"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/init(coder:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/init(fontSize:textColor:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/init(frame:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/borderWidth","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/bounds","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/intrinsicContentSize","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/isEmptyOfText","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/isHighlighted","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/roundedCorners"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/layoutSubviews()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/setTitle(_:for:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/setTitleColor(_:for:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/button"]},{"paths":["\/documentation\/lphud\/button"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"modules":[{"name":"LPHUD"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Button"}],"externalID":"c:@M@LPHUD@objc(cs)Button","title":"Button","symbolKind":"class","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Button"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Button","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.LPHUD/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.LPHUD/objc(pl)UISpringLoadedInteractionSupporting":{"type":"unresolvable","title":"UIKit.UISpringLoadedInteractionSupporting","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UISpringLoadedInteractionSupporting"},"doc://org.cocoapods.LPHUD/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.LPHUD/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s7CVarArgP"},"doc://org.cocoapods.LPHUD/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button/init(fontSize:textColor:)":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/init(fontSize:textColor:)","abstract":[{"text":"Creates a new button.","type":"text"}],"url":"\/documentation\/lphud\/button\/init(fontsize:textcolor:)","title":"init(fontSize:textColor:)","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fontSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"textColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?)","kind":"text"}],"kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"abstract":[],"role":"collection","kind":"symbol","type":"topic","title":"LPHUD","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","url":"\/documentation\/lphud"},"doc://org.cocoapods.LPHUD/objc(pl)UIContextMenuInteractionDelegate":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIContextMenuInteractionDelegate","title":"UIKit.UIContextMenuInteractionDelegate"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button/setTitleColor(_:for:)":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/setTitleColor(_:for:)","abstract":[{"text":"Sets the color of the title to use for the specified state.","type":"text"}],"url":"\/documentation\/lphud\/button\/settitlecolor(_:for:)","title":"setTitleColor(_:for:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setTitleColor:forState:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTitleColor"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl"},{"text":".","kind":"text"},{"text":"State","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlState"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button/init(coder:)":{"abstract":[{"type":"text","text":"Creates a new button with data in an unarchiver."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/init(coder:)","url":"\/documentation\/lphud\/button\/init(coder:)","type":"topic","title":"init(coder:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"},"doc://org.cocoapods.LPHUD/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting":{"type":"unresolvable","title":"UIKit.UIAccessibilityContentSizeCategoryImageAdjusting","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting"},"doc://org.cocoapods.LPHUD/objc(cs)UIButton":{"type":"unresolvable","title":"UIButton","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(cs)UIButton"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button/borderWidth":{"abstract":[{"type":"text","text":"Button border width. "},{"type":"codeVoice","code":"Default to 1"},{"text":".","type":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/borderWidth","url":"\/documentation\/lphud\/button\/borderwidth","type":"topic","title":"borderWidth","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"borderWidth","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"kind":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button/init(frame:)":{"abstract":[{"type":"text","text":"Creates a new button with the specified frame."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/init(frame:)","url":"\/documentation\/lphud\/button\/init(frame:)","type":"topic","title":"init(frame:)","role":"symbol","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSCoding"},"doc://org.cocoapods.LPHUD/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearance"},"doc://org.cocoapods.LPHUD/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.LPHUD\/SH"},"doc://org.cocoapods.LPHUD/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.LPHUD/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.LPHUD\/SQ"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button/roundedCorners":{"kind":"symbol","url":"\/documentation\/lphud\/button\/roundedcorners","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/roundedCorners","title":"roundedCorners","role":"symbol","abstract":[{"text":"The rounded corner mode of the button. ","type":"text"},{"type":"codeVoice","code":"Default to .full"},{"text":".","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"roundedCorners"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RoundedCorners","preciseIdentifier":"s:5LPHUD14RoundedCornersO"}],"type":"topic"},"doc://org.cocoapods.LPHUD/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.LPHUD/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s8SendableP"},"doc://org.cocoapods.LPHUD/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button/isEmptyOfText":{"abstract":[{"text":"Whether the text displayed by the button is nil and empty.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/isEmptyOfText","url":"\/documentation\/lphud\/button\/isemptyoftext","type":"topic","title":"isEmptyOfText","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEmptyOfText"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button":{"kind":"symbol","url":"\/documentation\/lphud\/button","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button","title":"Button","role":"symbol","abstract":[{"type":"text","text":"A control that executes your custom code in response to user interactions."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Button","kind":"identifier"}],"navigatorTitle":[{"text":"Button","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.LPHUD/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button/bounds":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/bounds","kind":"symbol","type":"topic","role":"symbol","title":"bounds","url":"\/documentation\/lphud\/button\/bounds","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bounds","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}],"abstract":[{"text":"The bounds rectangle, which describes the button’s location and size in its own coordinate system.","type":"text"}],"navigatorTitle":[{"text":"bounds","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button/intrinsicContentSize":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/intrinsicContentSize","abstract":[{"type":"text","text":"The natural size for the receiving view, considering only properties of the view itself."}],"url":"\/documentation\/lphud\/button\/intrinsiccontentsize","title":"intrinsicContentSize","type":"topic","role":"symbol","navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"}],"kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button/isHighlighted":{"abstract":[{"text":"A Boolean value indicating whether the control draws a highlight.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/isHighlighted","url":"\/documentation\/lphud\/button\/ishighlighted","type":"topic","title":"isHighlighted","role":"symbol","navigatorTitle":[{"text":"highlighted","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isHighlighted"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)CALayerDelegate","type":"unresolvable","title":"QuartzCore.CALayerDelegate"},"doc://org.cocoapods.LPHUD/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUDExtended":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"HUDExtended","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/lphud\/hudextended","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended","navigatorTitle":[{"text":"HUDExtended","kind":"identifier"}],"title":"HUDExtended","type":"topic","abstract":[{"type":"text","text":"Protocol describing the "},{"type":"codeVoice","code":"h"},{"type":"text","text":" extension points for HUD extended types."}]},"doc://org.cocoapods.LPHUD/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://org.cocoapods.LPHUD/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.LPHUD/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button/setTitle(_:for:)":{"abstract":[{"text":"Sets the title to use for the specified state.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/setTitle(_:for:)","url":"\/documentation\/lphud\/button\/settitle(_:for:)","type":"topic","title":"setTitle(_:for:)","role":"symbol","navigatorTitle":[{"text":"setTitle:forState:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setTitle","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlState","text":"State"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button/layoutSubviews()":{"url":"\/documentation\/lphud\/button\/layoutsubviews()","role":"symbol","type":"topic","title":"layoutSubviews()","abstract":[{"type":"text","text":"Lays out subviews."}],"kind":"symbol","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.LPHUD/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"Button","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"Button"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"Button","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/bounds","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/intrinsicContentSize","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/isHighlighted"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/init(coder:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/init(frame:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/layoutSubviews()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/setTitle(_:for:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/setTitleColor(_:for:)"]}],"op":"replace"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.LPHUD\/objc(cs)UIButton"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"Button","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1setTitleColor(_:for:)\/title","value":"setTitleColor:forState:"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1setTitleColor(_:for:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setTitleColor:forState:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1init(coder:)\/title","value":"initWithCoder:"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1init(frame:)\/title","value":"initWithFrame:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithFrame:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1init(frame:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button\/title","value":"Button"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button\/fragments","value":[{"text":"Button","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1bounds\/title","value":"bounds"},{"value":[{"kind":"identifier","text":"bounds"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1bounds\/fragments"},{"op":"replace","value":"intrinsicContentSize","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1intrinsicContentSize\/title"},{"op":"replace","value":[{"text":"intrinsicContentSize","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1intrinsicContentSize\/fragments"},{"value":"highlighted","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1isHighlighted\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1isHighlighted\/fragments","value":[{"text":"highlighted","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1setTitle(_:for:)\/title","op":"replace","value":"setTitle:forState:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1setTitle(_:for:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setTitle:forState:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1layoutSubviews()\/title","value":"layoutSubviews","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1layoutSubviews()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}