{"kind":"symbol","metadata":{"symbolKind":"protocol","role":"symbol","roleHeading":"Protocol","externalID":"s:5LPHUD19DisplayLinkDelegateP","title":"DisplayLinkDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DisplayLinkDelegate"}],"navigatorTitle":[{"text":"DisplayLinkDelegate","kind":"identifier"}],"modules":[{"name":"LPHUD"}]},"abstract":[{"text":"The methods adopted by the object that allows your app to synchronize its drawing to the refresh rate of the display.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/DisplayLinkDelegate\/updateScreenInDisplayLink()"],"title":"Instance Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/displaylinkdelegate"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DisplayLinkDelegate","kind":"identifier"},{"text":" : AnyObject","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/DisplayLinkDelegate"},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView"],"title":"Conforming Types","type":"conformingTypes","kind":"relationships"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/DisplayLinkDelegate":{"type":"topic","kind":"symbol","url":"\/documentation\/lphud\/displaylinkdelegate","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/DisplayLinkDelegate","role":"symbol","abstract":[{"type":"text","text":"The methods adopted by the object that allows your app to synchronize its drawing to the refresh rate of the display."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DisplayLinkDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DisplayLinkDelegate"}],"title":"DisplayLinkDelegate"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContentView"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContentView"}],"url":"\/documentation\/lphud\/contentview","abstract":[{"text":"The content view of the HUD object. The view containing the labels, button and indicator (or customView).","type":"text"},{"type":"text","text":" "},{"text":"The HUD object places the content in this view in front of any background views.","type":"text"}],"title":"ContentView","role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProgressView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView","abstract":[{"type":"text","text":"A view that depicts the progress of a task over time."}],"type":"topic","title":"ProgressView","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ProgressView"}],"kind":"symbol","url":"\/documentation\/lphud\/progressview"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"abstract":[],"role":"collection","kind":"symbol","type":"topic","title":"LPHUD","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","url":"\/documentation\/lphud"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/DisplayLinkDelegate/updateScreenInDisplayLink()":{"kind":"symbol","required":true,"abstract":[{"type":"text","text":"Tells the delegate that the refreshing the screen only every frame draw."}],"role":"symbol","type":"topic","title":"updateScreenInDisplayLink()","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/DisplayLinkDelegate\/updateScreenInDisplayLink()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateScreenInDisplayLink"},{"text":"()","kind":"text"}],"url":"\/documentation\/lphud\/displaylinkdelegate\/updatescreenindisplaylink()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ContentView\/title","value":"ContentView"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ContentView\/fragments","op":"replace","value":[{"text":"ContentView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/title","value":"ProgressView"},{"value":[{"text":"ProgressView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/fragments","op":"replace"}]}]}