{"metadata":{"title":"progress(_:)","extendedModule":"LPHUD","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"progress"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)ProgressView","text":"ProgressView"},{"text":".","kind":"text"},{"text":"Style","preciseIdentifier":"s:5LPHUD12ProgressViewC5StyleO","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD","text":"HUD"},{"text":".","kind":"text"},{"text":"Mode","kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD3HUDC4ModeO"}],"externalID":"s:5LPHUD3HUDC4ModeO8progressyAeA12ProgressViewC5StyleOFZ","role":"symbol","modules":[{"name":"LPHUD"}],"symbolKind":"method","roleHeading":"Type Method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/Mode-swift.enum"]]},"abstract":[{"type":"text","text":"Creates a progress view with the specified style."}],"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/Mode-swift.enum\/progress(_:)-21973","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/hud\/mode-swift.enum\/progress(_:)-21973"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"progress","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"style","kind":"internalParam"},{"kind":"text","text":": "},{"text":"ProgressView","preciseIdentifier":"c:@M@LPHUD@objc(cs)ProgressView","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD12ProgressViewC5StyleO","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/Style-swift.enum"},{"text":") -> ","kind":"text"},{"text":"HUD","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD"},{"text":".","kind":"text"},{"preciseIdentifier":"s:5LPHUD3HUDC4ModeO","text":"Mode","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/Mode-swift.enum"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"style","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A constant that specifies the style of the object to be created."},{"text":" ","type":"text"},{"text":"See ProgressView.Style for descriptions of the style constants.","type":"text"}]}]}]},{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"text":"An initialized HUD.Mode constant.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"type":"topic","url":"\/documentation\/lphud","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","title":"LPHUD","role":"collection"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD":{"navigatorTitle":[{"kind":"identifier","text":"HUD"}],"title":"HUD","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","url":"\/documentation\/lphud\/hud","abstract":[{"text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HUD","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/Mode-swift.enum/progress(_:)-21973":{"abstract":[{"type":"text","text":"Creates a progress view with the specified style."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/Mode-swift.enum\/progress(_:)-21973","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"progress","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)ProgressView","kind":"typeIdentifier","text":"ProgressView"},{"text":".","kind":"text"},{"preciseIdentifier":"s:5LPHUD12ProgressViewC5StyleO","kind":"typeIdentifier","text":"Style"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD","text":"HUD"},{"kind":"text","text":"."},{"text":"Mode","preciseIdentifier":"s:5LPHUD3HUDC4ModeO","kind":"typeIdentifier"}],"url":"\/documentation\/lphud\/hud\/mode-swift.enum\/progress(_:)-21973","role":"symbol","kind":"symbol","type":"topic","title":"progress(_:)"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/Mode-swift.enum":{"title":"HUD.Mode","url":"\/documentation\/lphud\/hud\/mode-swift.enum","navigatorTitle":[{"text":"Mode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Mode"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/Mode-swift.enum","abstract":[],"kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView","type":"topic","navigatorTitle":[{"text":"ProgressView","kind":"identifier"}],"abstract":[{"type":"text","text":"A view that depicts the progress of a task over time."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ProgressView","kind":"identifier"}],"role":"symbol","title":"ProgressView","url":"\/documentation\/lphud\/progressview","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/Style-swift.enum":{"abstract":[{"type":"text","text":"The styles permitted for the progress bar."}],"role":"symbol","url":"\/documentation\/lphud\/progressview\/style-swift.enum","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/Style-swift.enum","title":"ProgressView.Style","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Style"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/title","op":"replace","value":"HUD"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/fragments","value":[{"kind":"identifier","text":"HUD"}]},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/title","op":"replace","value":"ProgressView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/fragments","value":[{"text":"ProgressView","kind":"identifier"}]}]}]}